// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connector struct {
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	Role        pgtype.Text        `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ConnectorSetting struct {
	ID            int32  `json:"id"`
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

type Plan struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	SyncSource string             `json:"sync_source"`
	FilePath   string             `json:"file_path"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

type PlanComment struct {
	ID        int32              `json:"id"`
	PlanID    int64              `json:"plan_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlanTag struct {
	PlanID     int64              `json:"plan_id"`
	TagID      int64              `json:"tag_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type PlanVersion struct {
	ID            int32              `json:"id"`
	PlanID        int64              `json:"plan_id"`
	VersionNumber int64              `json:"version_number"`
	FilePath      string             `json:"file_path"`
	Content       string             `json:"content"`
	WordCount     int64              `json:"word_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	VariableName  string             `json:"variable_name"`
	VariableType  string             `json:"variable_type"`
	StringValue   pgtype.Text        `json:"string_value"`
	NumberValue   pgtype.Float8      `json:"number_value"`
	BooleanValue  pgtype.Bool        `json:"boolean_value"`
	DatetimeValue pgtype.Timestamptz `json:"datetime_value"`
}

type Tag struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
