// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Javier162380/busquets/internal/clipboard (interfaces: Clipboard)

// Package clipboard_test is a generated GoMock package.
package clipboard_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClipboard is a mock of Clipboard interface.
type MockClipboard struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardMockRecorder
}

// MockClipboardMockRecorder is the mock recorder for MockClipboard.
type MockClipboardMockRecorder struct {
	mock *MockClipboard
}

// NewMockClipboard creates a new mock instance.
func NewMockClipboard(ctrl *gomock.Controller) *MockClipboard {
	mock := &MockClipboard{ctrl: ctrl}
	mock.recorder = &MockClipboardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboard) EXPECT() *MockClipboardMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockClipboard) Write(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClipboardMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClipboard)(nil).Write), arg0, arg1)
}
