// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
	"time"
)

type Connector struct {
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	Enabled     bool        `json:"enabled"`
	Role        interface{} `json:"role"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type ConnectorSetting struct {
	ID            int64  `json:"id"`
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

type Plan struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	FilePath   string    `json:"file_path"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

type PlanTag struct {
	PlanID     int64     `json:"plan_id"`
	TagID      int64     `json:"tag_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type PlanVersion struct {
	ID            int64     `json:"id"`
	PlanID        int64     `json:"plan_id"`
	VersionNumber int64     `json:"version_number"`
	FilePath      string    `json:"file_path"`
	Content       string    `json:"content"`
	WordCount     int64     `json:"word_count"`
	CreatedAt     time.Time `json:"created_at"`
}

type Setting struct {
	VariableName  string          `json:"variable_name"`
	VariableType  string          `json:"variable_type"`
	StringValue   sql.NullString  `json:"string_value"`
	NumberValue   sql.NullFloat64 `json:"number_value"`
	BooleanValue  sql.NullBool    `json:"boolean_value"`
	DatetimeValue sql.NullTime    `json:"datetime_value"`
}

type Tag struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
