// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
	"time"
)

type Connector struct {
	Name        string    `json:"name"`
	DisplayName string    `json:"display_name"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ConnectorSetting struct {
	ID            int64  `json:"id"`
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

type Plan struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	FilePath   string    `json:"file_path"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

type PlanTag struct {
	PlanID     int64     `json:"plan_id"`
	TagID      int64     `json:"tag_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type PlanVersion struct {
	ID            int64     `json:"id"`
	PlanID        int64     `json:"plan_id"`
	VersionNumber int64     `json:"version_number"`
	FilePath      string    `json:"file_path"`
	Content       string    `json:"content"`
	WordCount     int64     `json:"word_count"`
	CreatedAt     time.Time `json:"created_at"`
}

type Session struct {
	ID             int64          `json:"id"`
	SessionUuid    string         `json:"session_uuid"`
	ProjectPath    string         `json:"project_path"`
	ProjectName    string         `json:"project_name"`
	JsonlFilePath  string         `json:"jsonl_file_path"`
	PlanID         sql.NullInt64  `json:"plan_id"`
	Status         string         `json:"status"`
	MessageCount   int64          `json:"message_count"`
	FirstMessageAt sql.NullTime   `json:"first_message_at"`
	LastMessageAt  sql.NullTime   `json:"last_message_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Cwd            sql.NullString `json:"cwd"`
	GitBranch      sql.NullString `json:"git_branch"`
	Slug           sql.NullString `json:"slug"`
}

type SessionFileChange struct {
	ID         int64         `json:"id"`
	SessionID  int64         `json:"session_id"`
	MessageID  sql.NullInt64 `json:"message_id"`
	FilePath   string        `json:"file_path"`
	ChangeType string        `json:"change_type"`
	DetectedAt time.Time     `json:"detected_at"`
}

type SessionMessage struct {
	ID             int64          `json:"id"`
	SessionID      int64          `json:"session_id"`
	MessageUuid    string         `json:"message_uuid"`
	ParentUuid     sql.NullString `json:"parent_uuid"`
	MessageType    string         `json:"message_type"`
	MessageSubtype sql.NullString `json:"message_subtype"`
	Content        sql.NullString `json:"content"`
	Role           sql.NullString `json:"role"`
	Timestamp      time.Time      `json:"timestamp"`
	Cwd            sql.NullString `json:"cwd"`
	GitBranch      sql.NullString `json:"git_branch"`
	IsMeta         sql.NullBool   `json:"is_meta"`
	IsSidechain    sql.NullBool   `json:"is_sidechain"`
	CreatedAt      time.Time      `json:"created_at"`
}

type SessionTodo struct {
	ID         int64          `json:"id"`
	SessionID  int64          `json:"session_id"`
	MessageID  sql.NullInt64  `json:"message_id"`
	Content    string         `json:"content"`
	Status     string         `json:"status"`
	ActiveForm sql.NullString `json:"active_form"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Setting struct {
	VariableName  string          `json:"variable_name"`
	VariableType  string          `json:"variable_type"`
	StringValue   sql.NullString  `json:"string_value"`
	NumberValue   sql.NullFloat64 `json:"number_value"`
	BooleanValue  sql.NullBool    `json:"boolean_value"`
	DatetimeValue sql.NullTime    `json:"datetime_value"`
}

type Tag struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
