// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const addTagToPlan = `-- name: AddTagToPlan :exec

INSERT INTO plan_tags (plan_id, tag_id, assigned_at)
VALUES (?, ?, ?)
`

type AddTagToPlanParams struct {
	PlanID     int64     `json:"plan_id"`
	TagID      int64     `json:"tag_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

// Plan-Tag association queries
func (q *Queries) AddTagToPlan(ctx context.Context, arg AddTagToPlanParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPlan, arg.PlanID, arg.TagID, arg.AssignedAt)
	return err
}

const cancelScheduledJob = `-- name: CancelScheduledJob :exec
UPDATE scheduled_jobs
SET cancelled = 1
WHERE job_id = ?
`

func (q *Queries) CancelScheduledJob(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, cancelScheduledJob, jobID)
	return err
}

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllConnectorSettings = `-- name: DeleteAllConnectorSettings :exec
DELETE FROM connector_settings WHERE connector_name = ?
`

func (q *Queries) DeleteAllConnectorSettings(ctx context.Context, connectorName string) error {
	_, err := q.db.ExecContext(ctx, deleteAllConnectorSettings, connectorName)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors WHERE name = ?
`

func (q *Queries) DeleteConnector(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteConnector, name)
	return err
}

const deleteConnectorSetting = `-- name: DeleteConnectorSetting :exec
DELETE FROM connector_settings WHERE connector_name = ? AND setting_key = ?
`

type DeleteConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

func (q *Queries) DeleteConnectorSetting(ctx context.Context, arg DeleteConnectorSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorSetting, arg.ConnectorName, arg.SettingKey)
	return err
}

const deleteExecutionsByJobID = `-- name: DeleteExecutionsByJobID :exec
DELETE FROM job_executions WHERE job_id = ?
`

func (q *Queries) DeleteExecutionsByJobID(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionsByJobID, jobID)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM background_jobs WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE file_name = ?
`

func (q *Queries) DeletePlan(ctx context.Context, fileName string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, fileName)
	return err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :exec
DELETE FROM scheduled_jobs WHERE job_id = ?
`

func (q *Queries) DeleteScheduledJob(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduledJob, jobID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE variable_name = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, variableName string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, variableName)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteVersionsOlderThan = `-- name: DeleteVersionsOlderThan :exec
DELETE FROM plan_versions
WHERE plan_id = ? AND version_number <= ?
`

type DeleteVersionsOlderThanParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) DeleteVersionsOlderThan(ctx context.Context, arg DeleteVersionsOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, deleteVersionsOlderThan, arg.PlanID, arg.VersionNumber)
	return err
}

const disableAllConnectors = `-- name: DisableAllConnectors :exec
UPDATE connectors SET enabled = 0, updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) DisableAllConnectors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableAllConnectors)
	return err
}

const getConnectorByName = `-- name: GetConnectorByName :one

SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE name = ?
`

// Connector queries
func (q *Queries) GetConnectorByName(ctx context.Context, name string) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnectorByName, name)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorSetting = `-- name: GetConnectorSetting :one

SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = ? AND setting_key = ?
`

type GetConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

// Connector settings queries
func (q *Queries) GetConnectorSetting(ctx context.Context, arg GetConnectorSettingParams) (ConnectorSetting, error) {
	row := q.db.QueryRowContext(ctx, getConnectorSetting, arg.ConnectorName, arg.SettingKey)
	var i ConnectorSetting
	err := row.Scan(
		&i.ID,
		&i.ConnectorName,
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
	)
	return i, err
}

const getEnabledConnector = `-- name: GetEnabledConnector :one
SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE enabled = 1 LIMIT 1
`

func (q *Queries) GetEnabledConnector(ctx context.Context) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getEnabledConnector)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by FROM job_executions WHERE id = ? LIMIT 1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByID, id)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ExecutionNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id string) (BackgroundJob, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.AgentProvider,
		&i.AgentConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const getJobByPlanID = `-- name: GetJobByPlanID :many
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs WHERE plan_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetJobByPlanID(ctx context.Context, planID int64) ([]BackgroundJob, error) {
	rows, err := q.db.QueryContext(ctx, getJobByPlanID, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestExecution = `-- name: GetLatestExecution :one
SELECT id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by FROM job_executions
WHERE job_id = ?
ORDER BY execution_number DESC
LIMIT 1
`

func (q *Queries) GetLatestExecution(ctx context.Context, jobID string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getLatestExecution, jobID)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ExecutionNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) FROM plan_versions WHERE plan_id = ?
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, planID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, planID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getNextExecutionNumber = `-- name: GetNextExecutionNumber :one
SELECT COALESCE(MAX(execution_number), 0) + 1 AS next_number
FROM job_executions
WHERE job_id = ?
`

func (q *Queries) GetNextExecutionNumber(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextExecutionNumber, jobID)
	var next_number int64
	err := row.Scan(&next_number)
	return next_number, err
}

const getPlanByFileName = `-- name: GetPlanByFileName :one
SELECT id, file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE file_name = ? LIMIT 1
`

func (q *Queries) GetPlanByFileName(ctx context.Context, fileName string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByFileName, fileName)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanTags = `-- name: GetPlanTags :many
SELECT t.id, t.name, t.description, t.color, t.created_at, t.updated_at FROM tags t
JOIN plan_tags pt ON t.id = pt.tag_id
WHERE pt.plan_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetPlanTags(ctx context.Context, planID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getPlanTags, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanVersionByNumber = `-- name: GetPlanVersionByNumber :one
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ? AND version_number = ?
LIMIT 1
`

type GetPlanVersionByNumberParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) GetPlanVersionByNumber(ctx context.Context, arg GetPlanVersionByNumberParams) (PlanVersion, error) {
	row := q.db.QueryRowContext(ctx, getPlanVersionByNumber, arg.PlanID, arg.VersionNumber)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.VersionNumber,
		&i.FilePath,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanVersionHistory = `-- name: GetPlanVersionHistory :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ?
ORDER BY version_number DESC
LIMIT ? OFFSET ?
`

type GetPlanVersionHistoryParams struct {
	PlanID int64 `json:"plan_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetPlanVersionHistory(ctx context.Context, arg GetPlanVersionHistoryParams) ([]PlanVersion, error) {
	rows, err := q.db.QueryContext(ctx, getPlanVersionHistory, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansWithTag = `-- name: GetPlansWithTag :many
SELECT p.id, p.file_name, p.title, p.created_at, p.modified_at, p.file_size, p.word_count
FROM plans p
JOIN plan_tags pt ON p.id = pt.plan_id
WHERE pt.tag_id = ?
ORDER BY p.modified_at DESC
`

type GetPlansWithTagRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) GetPlansWithTag(ctx context.Context, tagID int64) ([]GetPlansWithTagRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlansWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlansWithTagRow{}
	for rows.Next() {
		var i GetPlansWithTagRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledJobByJobID = `-- name: GetScheduledJobByJobID :one
SELECT id, job_id, scheduled_at, cancelled, created_at FROM scheduled_jobs WHERE job_id = ? LIMIT 1
`

func (q *Queries) GetScheduledJobByJobID(ctx context.Context, jobID string) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduledJobByJobID, jobID)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.Cancelled,
		&i.CreatedAt,
	)
	return i, err
}

const getSettingByName = `-- name: GetSettingByName :one
SELECT variable_name, variable_type, string_value, number_value, boolean_value, datetime_value FROM settings WHERE variable_name = ? LIMIT 1
`

func (q *Queries) GetSettingByName(ctx context.Context, variableName string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByName, variableName)
	var i Setting
	err := row.Scan(
		&i.VariableName,
		&i.VariableType,
		&i.StringValue,
		&i.NumberValue,
		&i.BooleanValue,
		&i.DatetimeValue,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVersionCount = `-- name: GetVersionCount :one
SELECT COUNT(*) FROM plan_versions WHERE plan_id = ?
`

func (q *Queries) GetVersionCount(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVersionCount, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertExecution = `-- name: InsertExecution :one

INSERT INTO job_executions (id, job_id, execution_number, status, triggered_by, started_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by
`

type InsertExecutionParams struct {
	ID              string       `json:"id"`
	JobID           string       `json:"job_id"`
	ExecutionNumber int64        `json:"execution_number"`
	Status          string       `json:"status"`
	TriggeredBy     string       `json:"triggered_by"`
	StartedAt       sql.NullTime `json:"started_at"`
}

// Job execution queries
func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, insertExecution,
		arg.ID,
		arg.JobID,
		arg.ExecutionNumber,
		arg.Status,
		arg.TriggeredBy,
		arg.StartedAt,
	)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ExecutionNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one

INSERT INTO background_jobs (id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at
`

type InsertJobParams struct {
	ID            string         `json:"id"`
	PlanID        int64          `json:"plan_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	AgentProvider string         `json:"agent_provider"`
	AgentConfig   string         `json:"agent_config"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Background job queries
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (BackgroundJob, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.PlanID,
		arg.Name,
		arg.Description,
		arg.AgentProvider,
		arg.AgentConfig,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.AgentProvider,
		&i.AgentConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO plans (file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanParams struct {
	FileName   string    `json:"file_name"`
	FilePath   string    `json:"file_path"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertPlan,
		arg.FileName,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
	)
	return err
}

const insertPlanVersion = `-- name: InsertPlanVersion :exec
INSERT INTO plan_versions (plan_id, version_number, file_path, content, word_count, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPlanVersionParams struct {
	PlanID        int64     `json:"plan_id"`
	VersionNumber int64     `json:"version_number"`
	FilePath      string    `json:"file_path"`
	Content       string    `json:"content"`
	WordCount     int64     `json:"word_count"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertPlanVersion(ctx context.Context, arg InsertPlanVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertPlanVersion,
		arg.PlanID,
		arg.VersionNumber,
		arg.FilePath,
		arg.Content,
		arg.WordCount,
		arg.CreatedAt,
	)
	return err
}

const insertScheduledJob = `-- name: InsertScheduledJob :one

INSERT INTO scheduled_jobs (id, job_id, scheduled_at, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, job_id, scheduled_at, cancelled, created_at
`

type InsertScheduledJobParams struct {
	ID          string    `json:"id"`
	JobID       string    `json:"job_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	CreatedAt   time.Time `json:"created_at"`
}

// Scheduled job queries
func (q *Queries) InsertScheduledJob(ctx context.Context, arg InsertScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, insertScheduledJob,
		arg.ID,
		arg.JobID,
		arg.ScheduledAt,
		arg.CreatedAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.Cancelled,
		&i.CreatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO tags (name, description, color, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, color, created_at, updated_at
`

type InsertTagParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Tag queries
func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, insertTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
`

type ListAllPlansRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansRow{}
	for rows.Next() {
		var i ListAllPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithPagination = `-- name: ListAllPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
LIMIT ? OFFSET ?
`

type ListAllPlansWithPaginationParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllPlansWithPaginationRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) ListAllPlansWithPagination(ctx context.Context, arg ListAllPlansWithPaginationParams) ([]ListAllPlansWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlansWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithPaginationRow{}
	for rows.Next() {
		var i ListAllPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithTags = `-- name: ListAllPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    COALESCE(t.tag_ids, '') AS tag_ids,
    COALESCE(t.tag_names, '') AS tag_names
FROM plans p
LEFT JOIN (
    SELECT
        pt.plan_id,
        GROUP_CONCAT(DISTINCT t.id) AS tag_ids,
        GROUP_CONCAT(DISTINCT t.name) AS tag_names
    FROM plan_tags pt
    JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
ORDER BY p.modified_at DESC
`

type ListAllPlansWithTagsRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
	TagIds     string    `json:"tag_ids"`
	TagNames   string    `json:"tag_names"`
}

func (q *Queries) ListAllPlansWithTags(ctx context.Context) ([]ListAllPlansWithTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlansWithTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithTagsRow{}
	for rows.Next() {
		var i ListAllPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, description, color, created_at, updated_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorSettings = `-- name: ListConnectorSettings :many
SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = ?
`

func (q *Queries) ListConnectorSettings(ctx context.Context, connectorName string) ([]ConnectorSetting, error) {
	rows, err := q.db.QueryContext(ctx, listConnectorSettings, connectorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorSetting{}
	for rows.Next() {
		var i ConnectorSetting
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorName,
			&i.SettingKey,
			&i.SettingValue,
			&i.IsSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT name, display_name, enabled, created_at, updated_at FROM connectors ORDER BY name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]Connector, error) {
	rows, err := q.db.QueryContext(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueScheduledJobs = `-- name: ListDueScheduledJobs :many
SELECT id, job_id, scheduled_at, cancelled, created_at FROM scheduled_jobs
WHERE scheduled_at <= ?
  AND cancelled = 0
ORDER BY scheduled_at ASC
`

func (q *Queries) ListDueScheduledJobs(ctx context.Context, scheduledAt time.Time) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledJobs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ScheduledAt,
			&i.Cancelled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by FROM job_executions
WHERE (? IS NULL OR job_id = ?)
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListExecutionsParams struct {
	Column1 interface{} `json:"column_1"`
	JobID   string      `json:"job_id"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]JobExecution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutions,
		arg.Column1,
		arg.JobID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobExecution{}
	for rows.Next() {
		var i JobExecution
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ExecutionNumber,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.OutputLog,
			&i.ErrorMessage,
			&i.TriggeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsWithContext = `-- name: ListExecutionsWithContext :many
SELECT
    je.id, je.job_id, je.execution_number, je.status, je.started_at, je.completed_at, je.exit_code, je.output_log, je.error_message, je.triggered_by,
    bj.name AS job_name,
    p.file_name AS plan_name
FROM job_executions je
JOIN background_jobs bj ON je.job_id = bj.id
JOIN plans p ON bj.plan_id = p.id
WHERE (? IS NULL OR je.job_id = ?)
ORDER BY je.started_at DESC
LIMIT ? OFFSET ?
`

type ListExecutionsWithContextParams struct {
	Column1 interface{} `json:"column_1"`
	JobID   string      `json:"job_id"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListExecutionsWithContextRow struct {
	ID              string         `json:"id"`
	JobID           string         `json:"job_id"`
	ExecutionNumber int64          `json:"execution_number"`
	Status          string         `json:"status"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	ExitCode        sql.NullInt64  `json:"exit_code"`
	OutputLog       sql.NullString `json:"output_log"`
	ErrorMessage    sql.NullString `json:"error_message"`
	TriggeredBy     string         `json:"triggered_by"`
	JobName         string         `json:"job_name"`
	PlanName        string         `json:"plan_name"`
}

func (q *Queries) ListExecutionsWithContext(ctx context.Context, arg ListExecutionsWithContextParams) ([]ListExecutionsWithContextRow, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsWithContext,
		arg.Column1,
		arg.JobID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsWithContextRow{}
	for rows.Next() {
		var i ListExecutionsWithContextRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ExecutionNumber,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.OutputLog,
			&i.ErrorMessage,
			&i.TriggeredBy,
			&i.JobName,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs
WHERE (? IS NULL OR plan_id = ?)
  AND (? IS NULL OR status = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListJobsParams struct {
	Column1 interface{} `json:"column_1"`
	PlanID  int64       `json:"plan_id"`
	Column3 interface{} `json:"column_3"`
	Status  string      `json:"status"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]BackgroundJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs,
		arg.Column1,
		arg.PlanID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithPlans = `-- name: ListJobsWithPlans :many
SELECT
    bj.id, bj.plan_id, bj.name, bj.description, bj.agent_provider, bj.agent_config, bj.status, bj.created_at, bj.updated_at, bj.last_run_at,
    p.file_name AS plan_name,
    p.file_path AS plan_path
FROM background_jobs bj
JOIN plans p ON bj.plan_id = p.id
WHERE (? IS NULL OR bj.plan_id = ?)
  AND (? IS NULL OR bj.status = ?)
ORDER BY bj.created_at DESC
LIMIT ? OFFSET ?
`

type ListJobsWithPlansParams struct {
	Column1 interface{} `json:"column_1"`
	PlanID  int64       `json:"plan_id"`
	Column3 interface{} `json:"column_3"`
	Status  string      `json:"status"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type ListJobsWithPlansRow struct {
	ID            string         `json:"id"`
	PlanID        int64          `json:"plan_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	AgentProvider string         `json:"agent_provider"`
	AgentConfig   string         `json:"agent_config"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	LastRunAt     sql.NullTime   `json:"last_run_at"`
	PlanName      string         `json:"plan_name"`
	PlanPath      string         `json:"plan_path"`
}

func (q *Queries) ListJobsWithPlans(ctx context.Context, arg ListJobsWithPlansParams) ([]ListJobsWithPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsWithPlans,
		arg.Column1,
		arg.PlanID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsWithPlansRow{}
	for rows.Next() {
		var i ListJobsWithPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.PlanName,
			&i.PlanPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPlansFromTag = `-- name: RemoveAllPlansFromTag :exec
DELETE FROM plan_tags WHERE tag_id = ?
`

func (q *Queries) RemoveAllPlansFromTag(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllPlansFromTag, tagID)
	return err
}

const removeAllTagsFromPlan = `-- name: RemoveAllTagsFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = ?
`

func (q *Queries) RemoveAllTagsFromPlan(ctx context.Context, planID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromPlan, planID)
	return err
}

const removeTagFromPlan = `-- name: RemoveTagFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = ? AND tag_id = ?
`

type RemoveTagFromPlanParams struct {
	PlanID int64 `json:"plan_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPlan(ctx context.Context, arg RemoveTagFromPlanParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPlan, arg.PlanID, arg.TagID)
	return err
}

const searchPlans = `-- name: SearchPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE ? OR content LIKE ?
ORDER BY modified_at DESC
`

type SearchPlansParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) SearchPlans(ctx context.Context, arg SearchPlansParams) ([]SearchPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlans, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansRow{}
	for rows.Next() {
		var i SearchPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithPagination = `-- name: SearchPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE ? OR content LIKE ?
ORDER BY modified_at DESC
LIMIT ? OFFSET ?
`

type SearchPlansWithPaginationParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type SearchPlansWithPaginationRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) SearchPlansWithPagination(ctx context.Context, arg SearchPlansWithPaginationParams) ([]SearchPlansWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlansWithPagination,
		arg.Title,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithPaginationRow{}
	for rows.Next() {
		var i SearchPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithTags = `-- name: SearchPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    COALESCE(t.tag_ids, '') AS tag_ids,
    COALESCE(t.tag_names, '') AS tag_names
FROM plans p
LEFT JOIN (
    SELECT
        pt.plan_id,
        GROUP_CONCAT(DISTINCT t.id) AS tag_ids,
        GROUP_CONCAT(DISTINCT t.name) AS tag_names
    FROM plan_tags pt
    JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
WHERE p.title LIKE ? OR p.content LIKE ?
ORDER BY p.modified_at DESC
`

type SearchPlansWithTagsParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansWithTagsRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
	TagIds     string    `json:"tag_ids"`
	TagNames   string    `json:"tag_names"`
}

func (q *Queries) SearchPlansWithTags(ctx context.Context, arg SearchPlansWithTagsParams) ([]SearchPlansWithTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlansWithTags, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithTagsRow{}
	for rows.Next() {
		var i SearchPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVersionsByContent = `-- name: SearchVersionsByContent :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ? AND content LIKE ?
ORDER BY version_number DESC
`

type SearchVersionsByContentParams struct {
	PlanID  int64  `json:"plan_id"`
	Content string `json:"content"`
}

func (q *Queries) SearchVersionsByContent(ctx context.Context, arg SearchVersionsByContentParams) ([]PlanVersion, error) {
	rows, err := q.db.QueryContext(ctx, searchVersionsByContent, arg.PlanID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorEnabled = `-- name: SetConnectorEnabled :exec
UPDATE connectors SET enabled = 1, updated_at = CURRENT_TIMESTAMP WHERE name = ?
`

func (q *Queries) SetConnectorEnabled(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, setConnectorEnabled, name)
	return err
}

const updateExecution = `-- name: UpdateExecution :exec
UPDATE job_executions
SET status = ?,
    started_at = COALESCE(?, started_at),
    completed_at = COALESCE(?, completed_at),
    exit_code = COALESCE(?, exit_code),
    output_log = COALESCE(?, output_log),
    error_message = COALESCE(?, error_message)
WHERE id = ?
`

type UpdateExecutionParams struct {
	Status       string         `json:"status"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	OutputLog    sql.NullString `json:"output_log"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) error {
	_, err := q.db.ExecContext(ctx, updateExecution,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ExitCode,
		arg.OutputLog,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE background_jobs
SET name = COALESCE(?, name),
    description = COALESCE(?, description),
    agent_config = COALESCE(?, agent_config),
    status = COALESCE(?, status),
    updated_at = ?
WHERE id = ?
`

type UpdateJobParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	AgentConfig string         `json:"agent_config"`
	Status      string         `json:"status"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Name,
		arg.Description,
		arg.AgentConfig,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE background_jobs
SET status = ?,
    last_run_at = COALESCE(?, last_run_at),
    updated_at = ?
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status    string       `json:"status"`
	LastRunAt sql.NullTime `json:"last_run_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET title = ?, content = ?, modified_at = ?, indexed_at = ?, file_size = ?, word_count = ?
WHERE file_name = ?
`

type UpdatePlanParams struct {
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
	FileName   string    `json:"file_name"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Title,
		arg.Content,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
		arg.FileName,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags
SET name = ?, description = ?, color = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTagParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	return err
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO connectors (name, display_name, enabled)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertConnectorParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnector, arg.Name, arg.DisplayName, arg.Enabled)
	return err
}

const upsertConnectorSetting = `-- name: UpsertConnectorSetting :exec
INSERT INTO connector_settings (connector_name, setting_key, setting_value, is_secret)
VALUES (?, ?, ?, ?)
ON CONFLICT(connector_name, setting_key) DO UPDATE SET
    setting_value = excluded.setting_value,
    is_secret = excluded.is_secret
`

type UpsertConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

func (q *Queries) UpsertConnectorSetting(ctx context.Context, arg UpsertConnectorSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectorSetting,
		arg.ConnectorName,
		arg.SettingKey,
		arg.SettingValue,
		arg.IsSecret,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (variable_name, variable_type, string_value, number_value, boolean_value, datetime_value)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(variable_name) DO UPDATE SET
    variable_type = excluded.variable_type,
    string_value = excluded.string_value,
    number_value = excluded.number_value,
    boolean_value = excluded.boolean_value,
    datetime_value = excluded.datetime_value
`

type UpsertSettingParams struct {
	VariableName  string          `json:"variable_name"`
	VariableType  string          `json:"variable_type"`
	StringValue   sql.NullString  `json:"string_value"`
	NumberValue   sql.NullFloat64 `json:"number_value"`
	BooleanValue  sql.NullBool    `json:"boolean_value"`
	DatetimeValue sql.NullTime    `json:"datetime_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.VariableName,
		arg.VariableType,
		arg.StringValue,
		arg.NumberValue,
		arg.BooleanValue,
		arg.DatetimeValue,
	)
	return err
}
