// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const addTagToPlan = `-- name: AddTagToPlan :exec

INSERT INTO plan_tags (plan_id, tag_id, assigned_at)
VALUES (?, ?, ?)
`

type AddTagToPlanParams struct {
	PlanID     int64     `json:"plan_id"`
	TagID      int64     `json:"tag_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

// Plan-Tag association queries
func (q *Queries) AddTagToPlan(ctx context.Context, arg AddTagToPlanParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPlan, arg.PlanID, arg.TagID, arg.AssignedAt)
	return err
}

const clearConnectorRole = `-- name: ClearConnectorRole :exec
UPDATE connectors SET role = NULL, updated_at = CURRENT_TIMESTAMP WHERE role = ?
`

func (q *Queries) ClearConnectorRole(ctx context.Context, role interface{}) error {
	_, err := q.db.ExecContext(ctx, clearConnectorRole, role)
	return err
}

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllConnectorSettings = `-- name: DeleteAllConnectorSettings :exec
DELETE FROM connector_settings WHERE connector_name = ?
`

func (q *Queries) DeleteAllConnectorSettings(ctx context.Context, connectorName string) error {
	_, err := q.db.ExecContext(ctx, deleteAllConnectorSettings, connectorName)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM plan_comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors WHERE name = ?
`

func (q *Queries) DeleteConnector(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteConnector, name)
	return err
}

const deleteConnectorSetting = `-- name: DeleteConnectorSetting :exec
DELETE FROM connector_settings WHERE connector_name = ? AND setting_key = ?
`

type DeleteConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

func (q *Queries) DeleteConnectorSetting(ctx context.Context, arg DeleteConnectorSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorSetting, arg.ConnectorName, arg.SettingKey)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE file_name = ? AND sync_source = ?
`

type DeletePlanParams struct {
	FileName   string `json:"file_name"`
	SyncSource string `json:"sync_source"`
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) error {
	_, err := q.db.ExecContext(ctx, deletePlan, arg.FileName, arg.SyncSource)
	return err
}

const deletePlanComments = `-- name: DeletePlanComments :exec
DELETE FROM plan_comments WHERE plan_id = ?
`

func (q *Queries) DeletePlanComments(ctx context.Context, planID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlanComments, planID)
	return err
}

const deletePlanVersions = `-- name: DeletePlanVersions :exec
DELETE FROM plan_versions WHERE plan_id = ?
`

func (q *Queries) DeletePlanVersions(ctx context.Context, planID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlanVersions, planID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE variable_name = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, variableName string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, variableName)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteVersionsOlderThan = `-- name: DeleteVersionsOlderThan :exec
DELETE FROM plan_versions
WHERE plan_id = ? AND version_number <= ?
`

type DeleteVersionsOlderThanParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) DeleteVersionsOlderThan(ctx context.Context, arg DeleteVersionsOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, deleteVersionsOlderThan, arg.PlanID, arg.VersionNumber)
	return err
}

const getConnectorByName = `-- name: GetConnectorByName :one

SELECT name, display_name, enabled, role, created_at, updated_at FROM connectors WHERE name = ?
`

// Connector queries
func (q *Queries) GetConnectorByName(ctx context.Context, name string) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnectorByName, name)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorByRole = `-- name: GetConnectorByRole :one
SELECT name, display_name, enabled, role, created_at, updated_at FROM connectors WHERE role = ? LIMIT 1
`

func (q *Queries) GetConnectorByRole(ctx context.Context, role interface{}) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnectorByRole, role)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorSetting = `-- name: GetConnectorSetting :one

SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = ? AND setting_key = ?
`

type GetConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

// Connector settings queries
func (q *Queries) GetConnectorSetting(ctx context.Context, arg GetConnectorSettingParams) (ConnectorSetting, error) {
	row := q.db.QueryRowContext(ctx, getConnectorSetting, arg.ConnectorName, arg.SettingKey)
	var i ConnectorSetting
	err := row.Scan(
		&i.ID,
		&i.ConnectorName,
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) FROM plan_versions WHERE plan_id = ?
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, planID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, planID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPlanByFileNameAndSource = `-- name: GetPlanByFileNameAndSource :one
SELECT id, file_name, sync_source, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE file_name = ? AND sync_source = ? LIMIT 1
`

type GetPlanByFileNameAndSourceParams struct {
	FileName   string `json:"file_name"`
	SyncSource string `json:"sync_source"`
}

func (q *Queries) GetPlanByFileNameAndSource(ctx context.Context, arg GetPlanByFileNameAndSourceParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByFileNameAndSource, arg.FileName, arg.SyncSource)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.SyncSource,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanCommentCounts = `-- name: GetPlanCommentCounts :many
SELECT plan_id, COUNT(*) AS comment_count FROM plan_comments GROUP BY plan_id
`

type GetPlanCommentCountsRow struct {
	PlanID       int64 `json:"plan_id"`
	CommentCount int64 `json:"comment_count"`
}

func (q *Queries) GetPlanCommentCounts(ctx context.Context) ([]GetPlanCommentCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlanCommentCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlanCommentCountsRow{}
	for rows.Next() {
		var i GetPlanCommentCountsRow
		if err := rows.Scan(&i.PlanID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanComments = `-- name: GetPlanComments :many
SELECT id, plan_id, content, created_at, updated_at FROM plan_comments WHERE plan_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetPlanComments(ctx context.Context, planID int64) ([]PlanComment, error) {
	rows, err := q.db.QueryContext(ctx, getPlanComments, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanComment{}
	for rows.Next() {
		var i PlanComment
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanTags = `-- name: GetPlanTags :many
SELECT t.id, t.name, t.description, t.color, t.created_at, t.updated_at FROM tags t
JOIN plan_tags pt ON t.id = pt.tag_id
WHERE pt.plan_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetPlanTags(ctx context.Context, planID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getPlanTags, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanVersionByNumber = `-- name: GetPlanVersionByNumber :one
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ? AND version_number = ?
LIMIT 1
`

type GetPlanVersionByNumberParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) GetPlanVersionByNumber(ctx context.Context, arg GetPlanVersionByNumberParams) (PlanVersion, error) {
	row := q.db.QueryRowContext(ctx, getPlanVersionByNumber, arg.PlanID, arg.VersionNumber)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.VersionNumber,
		&i.FilePath,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanVersionHistory = `-- name: GetPlanVersionHistory :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ?
ORDER BY version_number DESC
LIMIT ? OFFSET ?
`

type GetPlanVersionHistoryParams struct {
	PlanID int64 `json:"plan_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetPlanVersionHistory(ctx context.Context, arg GetPlanVersionHistoryParams) ([]PlanVersion, error) {
	rows, err := q.db.QueryContext(ctx, getPlanVersionHistory, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansWithTag = `-- name: GetPlansWithTag :many
SELECT p.id, p.file_name, p.sync_source, p.title, p.created_at, p.modified_at, p.file_size, p.word_count
FROM plans p
JOIN plan_tags pt ON p.id = pt.plan_id
WHERE pt.tag_id = ?
ORDER BY p.modified_at DESC
`

type GetPlansWithTagRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) GetPlansWithTag(ctx context.Context, tagID int64) ([]GetPlansWithTagRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlansWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlansWithTagRow{}
	for rows.Next() {
		var i GetPlansWithTagRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.SyncSource,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByName = `-- name: GetSettingByName :one
SELECT variable_name, variable_type, string_value, number_value, boolean_value, datetime_value FROM settings WHERE variable_name = ? LIMIT 1
`

func (q *Queries) GetSettingByName(ctx context.Context, variableName string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByName, variableName)
	var i Setting
	err := row.Scan(
		&i.VariableName,
		&i.VariableType,
		&i.StringValue,
		&i.NumberValue,
		&i.BooleanValue,
		&i.DatetimeValue,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagPlanCounts = `-- name: GetTagPlanCounts :many
SELECT t.name, COUNT(DISTINCT pt.plan_id) AS plan_count
FROM tags t
LEFT JOIN plan_tags pt ON t.id = pt.tag_id
GROUP BY t.id, t.name
ORDER BY t.name ASC
`

type GetTagPlanCountsRow struct {
	Name      string `json:"name"`
	PlanCount int64  `json:"plan_count"`
}

func (q *Queries) GetTagPlanCounts(ctx context.Context) ([]GetTagPlanCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagPlanCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagPlanCountsRow{}
	for rows.Next() {
		var i GetTagPlanCountsRow
		if err := rows.Scan(&i.Name, &i.PlanCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUntaggedPlanCount = `-- name: GetUntaggedPlanCount :one
SELECT COUNT(*) AS count FROM plans
WHERE id NOT IN (SELECT DISTINCT plan_id FROM plan_tags)
`

func (q *Queries) GetUntaggedPlanCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUntaggedPlanCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVersionCount = `-- name: GetVersionCount :one
SELECT COUNT(*) FROM plan_versions WHERE plan_id = ?
`

func (q *Queries) GetVersionCount(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVersionCount, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertComment = `-- name: InsertComment :one

INSERT INTO plan_comments (plan_id, content, created_at, updated_at)
VALUES (?, ?, ?, ?) RETURNING id, plan_id, content, created_at, updated_at
`

type InsertCommentParams struct {
	PlanID    int64     `json:"plan_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Comment queries
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (PlanComment, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.PlanID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PlanComment
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO plans (file_name, sync_source, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanParams struct {
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	FilePath   string    `json:"file_path"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertPlan,
		arg.FileName,
		arg.SyncSource,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
	)
	return err
}

const insertPlanVersion = `-- name: InsertPlanVersion :exec
INSERT INTO plan_versions (plan_id, version_number, file_path, content, word_count, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPlanVersionParams struct {
	PlanID        int64     `json:"plan_id"`
	VersionNumber int64     `json:"version_number"`
	FilePath      string    `json:"file_path"`
	Content       string    `json:"content"`
	WordCount     int64     `json:"word_count"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertPlanVersion(ctx context.Context, arg InsertPlanVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertPlanVersion,
		arg.PlanID,
		arg.VersionNumber,
		arg.FilePath,
		arg.Content,
		arg.WordCount,
		arg.CreatedAt,
	)
	return err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO tags (name, description, color, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, color, created_at, updated_at
`

type InsertTagParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Tag queries
func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, insertTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, file_name, sync_source, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
`

type ListAllPlansRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansRow{}
	for rows.Next() {
		var i ListAllPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.SyncSource,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithPagination = `-- name: ListAllPlansWithPagination :many
SELECT id, file_name, sync_source, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
LIMIT ? OFFSET ?
`

type ListAllPlansWithPaginationParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllPlansWithPaginationRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) ListAllPlansWithPagination(ctx context.Context, arg ListAllPlansWithPaginationParams) ([]ListAllPlansWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlansWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithPaginationRow{}
	for rows.Next() {
		var i ListAllPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.SyncSource,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithTags = `-- name: ListAllPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.sync_source,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    COALESCE(t.tag_ids, '') AS tag_ids,
    COALESCE(t.tag_names, '') AS tag_names
FROM plans p
LEFT JOIN (
    SELECT
        pt.plan_id,
        GROUP_CONCAT(DISTINCT t.id) AS tag_ids,
        GROUP_CONCAT(DISTINCT t.name) AS tag_names
    FROM plan_tags pt
    JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
ORDER BY p.modified_at DESC
`

type ListAllPlansWithTagsRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
	TagIds     string    `json:"tag_ids"`
	TagNames   string    `json:"tag_names"`
}

func (q *Queries) ListAllPlansWithTags(ctx context.Context) ([]ListAllPlansWithTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlansWithTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithTagsRow{}
	for rows.Next() {
		var i ListAllPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.SyncSource,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, description, color, created_at, updated_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorSettings = `-- name: ListConnectorSettings :many
SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = ?
`

func (q *Queries) ListConnectorSettings(ctx context.Context, connectorName string) ([]ConnectorSetting, error) {
	rows, err := q.db.QueryContext(ctx, listConnectorSettings, connectorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorSetting{}
	for rows.Next() {
		var i ConnectorSetting
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorName,
			&i.SettingKey,
			&i.SettingValue,
			&i.IsSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT name, display_name, enabled, role, created_at, updated_at FROM connectors ORDER BY name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]Connector, error) {
	rows, err := q.db.QueryContext(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntaggedPlans = `-- name: ListUntaggedPlans :many
SELECT id, file_name, sync_source, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE id NOT IN (SELECT DISTINCT plan_id FROM plan_tags)
ORDER BY modified_at DESC
`

type ListUntaggedPlansRow struct {
	ID         int64     `json:"id"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
}

func (q *Queries) ListUntaggedPlans(ctx context.Context) ([]ListUntaggedPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listUntaggedPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUntaggedPlansRow{}
	for rows.Next() {
		var i ListUntaggedPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.SyncSource,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPlansFromTag = `-- name: RemoveAllPlansFromTag :exec
DELETE FROM plan_tags WHERE tag_id = ?
`

func (q *Queries) RemoveAllPlansFromTag(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllPlansFromTag, tagID)
	return err
}

const removeAllTagsFromPlan = `-- name: RemoveAllTagsFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = ?
`

func (q *Queries) RemoveAllTagsFromPlan(ctx context.Context, planID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromPlan, planID)
	return err
}

const removeTagFromPlan = `-- name: RemoveTagFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = ? AND tag_id = ?
`

type RemoveTagFromPlanParams struct {
	PlanID int64 `json:"plan_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPlan(ctx context.Context, arg RemoveTagFromPlanParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPlan, arg.PlanID, arg.TagID)
	return err
}

const searchVersionsByContent = `-- name: SearchVersionsByContent :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = ? AND content LIKE ?
ORDER BY version_number DESC
`

type SearchVersionsByContentParams struct {
	PlanID  int64  `json:"plan_id"`
	Content string `json:"content"`
}

func (q *Queries) SearchVersionsByContent(ctx context.Context, arg SearchVersionsByContentParams) ([]PlanVersion, error) {
	rows, err := q.db.QueryContext(ctx, searchVersionsByContent, arg.PlanID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorRole = `-- name: SetConnectorRole :exec
UPDATE connectors SET role = ?, updated_at = CURRENT_TIMESTAMP WHERE name = ?
`

type SetConnectorRoleParams struct {
	Role interface{} `json:"role"`
	Name string      `json:"name"`
}

func (q *Queries) SetConnectorRole(ctx context.Context, arg SetConnectorRoleParams) error {
	_, err := q.db.ExecContext(ctx, setConnectorRole, arg.Role, arg.Name)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET title = ?, content = ?, modified_at = ?, indexed_at = ?, file_size = ?, word_count = ?
WHERE file_name = ? AND sync_source = ?
`

type UpdatePlanParams struct {
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	ModifiedAt time.Time `json:"modified_at"`
	IndexedAt  time.Time `json:"indexed_at"`
	FileSize   int64     `json:"file_size"`
	WordCount  int64     `json:"word_count"`
	FileName   string    `json:"file_name"`
	SyncSource string    `json:"sync_source"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Title,
		arg.Content,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
		arg.FileName,
		arg.SyncSource,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags
SET name = ?, description = ?, color = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTagParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	return err
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO connectors (name, display_name, enabled)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertConnectorParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnector, arg.Name, arg.DisplayName, arg.Enabled)
	return err
}

const upsertConnectorSetting = `-- name: UpsertConnectorSetting :exec
INSERT INTO connector_settings (connector_name, setting_key, setting_value, is_secret)
VALUES (?, ?, ?, ?)
ON CONFLICT(connector_name, setting_key) DO UPDATE SET
    setting_value = excluded.setting_value,
    is_secret = excluded.is_secret
`

type UpsertConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

func (q *Queries) UpsertConnectorSetting(ctx context.Context, arg UpsertConnectorSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectorSetting,
		arg.ConnectorName,
		arg.SettingKey,
		arg.SettingValue,
		arg.IsSecret,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (variable_name, variable_type, string_value, number_value, boolean_value, datetime_value)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(variable_name) DO UPDATE SET
    variable_type = excluded.variable_type,
    string_value = excluded.string_value,
    number_value = excluded.number_value,
    boolean_value = excluded.boolean_value,
    datetime_value = excluded.datetime_value
`

type UpsertSettingParams struct {
	VariableName  string          `json:"variable_name"`
	VariableType  string          `json:"variable_type"`
	StringValue   sql.NullString  `json:"string_value"`
	NumberValue   sql.NullFloat64 `json:"number_value"`
	BooleanValue  sql.NullBool    `json:"boolean_value"`
	DatetimeValue sql.NullTime    `json:"datetime_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.VariableName,
		arg.VariableType,
		arg.StringValue,
		arg.NumberValue,
		arg.BooleanValue,
		arg.DatetimeValue,
	)
	return err
}
