// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountPlans(ctx context.Context) (int64, error)
	DeletePlan(ctx context.Context, fileName string) error
	DeleteSetting(ctx context.Context, variableName string) error
	DeleteVersionsOlderThan(ctx context.Context, arg DeleteVersionsOlderThanParams) error
	GetLatestVersionNumber(ctx context.Context, planID int64) (interface{}, error)
	GetPlanByFileName(ctx context.Context, fileName string) (Plan, error)
	GetPlanVersionByNumber(ctx context.Context, arg GetPlanVersionByNumberParams) (PlanVersion, error)
	GetPlanVersionHistory(ctx context.Context, arg GetPlanVersionHistoryParams) ([]PlanVersion, error)
	GetSettingByName(ctx context.Context, variableName string) (Setting, error)
	GetVersionCount(ctx context.Context, planID int64) (int64, error)
	InsertPlan(ctx context.Context, arg InsertPlanParams) error
	InsertPlanVersion(ctx context.Context, arg InsertPlanVersionParams) error
	ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error)
	ListAllPlansWithPagination(ctx context.Context, arg ListAllPlansWithPaginationParams) ([]ListAllPlansWithPaginationRow, error)
	SearchPlans(ctx context.Context, arg SearchPlansParams) ([]SearchPlansRow, error)
	SearchPlansWithPagination(ctx context.Context, arg SearchPlansWithPaginationParams) ([]SearchPlansWithPaginationRow, error)
	SearchVersionsByContent(ctx context.Context, arg SearchVersionsByContentParams) ([]PlanVersion, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
