// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackgroundJob struct {
	ID            pgtype.UUID        `json:"id"`
	PlanID        int64              `json:"plan_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	AgentProvider string             `json:"agent_provider"`
	AgentConfig   string             `json:"agent_config"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastRunAt     pgtype.Timestamptz `json:"last_run_at"`
}

type Connector struct {
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ConnectorSetting struct {
	ID            int32  `json:"id"`
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

type JobExecution struct {
	ID              pgtype.UUID        `json:"id"`
	JobID           pgtype.UUID        `json:"job_id"`
	ExecutionNumber int64              `json:"execution_number"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ExitCode        pgtype.Int4        `json:"exit_code"`
	OutputLog       pgtype.Text        `json:"output_log"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	TriggeredBy     string             `json:"triggered_by"`
}

type Plan struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	FilePath   string             `json:"file_path"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

type PlanTag struct {
	PlanID     int64              `json:"plan_id"`
	TagID      int64              `json:"tag_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type PlanVersion struct {
	ID            int32              `json:"id"`
	PlanID        int64              `json:"plan_id"`
	VersionNumber int64              `json:"version_number"`
	FilePath      string             `json:"file_path"`
	Content       string             `json:"content"`
	WordCount     int64              `json:"word_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScheduledJob struct {
	ID          pgtype.UUID        `json:"id"`
	JobID       pgtype.UUID        `json:"job_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Cancelled   bool               `json:"cancelled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	VariableName  string             `json:"variable_name"`
	VariableType  string             `json:"variable_type"`
	StringValue   pgtype.Text        `json:"string_value"`
	NumberValue   pgtype.Float8      `json:"number_value"`
	BooleanValue  pgtype.Bool        `json:"boolean_value"`
	DatetimeValue pgtype.Timestamptz `json:"datetime_value"`
}

type Tag struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
