// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connector struct {
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ConnectorSetting struct {
	ID            int32  `json:"id"`
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

type Plan struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	FilePath   string             `json:"file_path"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

type PlanTag struct {
	PlanID     int64              `json:"plan_id"`
	TagID      int64              `json:"tag_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type PlanVersion struct {
	ID            int32              `json:"id"`
	PlanID        int64              `json:"plan_id"`
	VersionNumber int64              `json:"version_number"`
	FilePath      string             `json:"file_path"`
	Content       string             `json:"content"`
	WordCount     int64              `json:"word_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID             int32              `json:"id"`
	SessionUuid    string             `json:"session_uuid"`
	ProjectPath    string             `json:"project_path"`
	ProjectName    string             `json:"project_name"`
	JsonlFilePath  string             `json:"jsonl_file_path"`
	PlanID         pgtype.Int8        `json:"plan_id"`
	Status         string             `json:"status"`
	MessageCount   int64              `json:"message_count"`
	FirstMessageAt pgtype.Timestamptz `json:"first_message_at"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Cwd            pgtype.Text        `json:"cwd"`
	GitBranch      pgtype.Text        `json:"git_branch"`
	Slug           pgtype.Text        `json:"slug"`
}

type SessionFileChange struct {
	ID         int32              `json:"id"`
	SessionID  int64              `json:"session_id"`
	MessageID  pgtype.Int8        `json:"message_id"`
	FilePath   string             `json:"file_path"`
	ChangeType string             `json:"change_type"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

type SessionMessage struct {
	ID             int32              `json:"id"`
	SessionID      int64              `json:"session_id"`
	MessageUuid    string             `json:"message_uuid"`
	ParentUuid     pgtype.Text        `json:"parent_uuid"`
	MessageType    string             `json:"message_type"`
	MessageSubtype pgtype.Text        `json:"message_subtype"`
	Content        pgtype.Text        `json:"content"`
	Role           pgtype.Text        `json:"role"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	Cwd            pgtype.Text        `json:"cwd"`
	GitBranch      pgtype.Text        `json:"git_branch"`
	IsMeta         pgtype.Bool        `json:"is_meta"`
	IsSidechain    pgtype.Bool        `json:"is_sidechain"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SessionTodo struct {
	ID         int32              `json:"id"`
	SessionID  int64              `json:"session_id"`
	MessageID  pgtype.Int8        `json:"message_id"`
	Content    string             `json:"content"`
	Status     string             `json:"status"`
	ActiveForm pgtype.Text        `json:"active_form"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Setting struct {
	VariableName  string             `json:"variable_name"`
	VariableType  string             `json:"variable_type"`
	StringValue   pgtype.Text        `json:"string_value"`
	NumberValue   pgtype.Float8      `json:"number_value"`
	BooleanValue  pgtype.Bool        `json:"boolean_value"`
	DatetimeValue pgtype.Timestamptz `json:"datetime_value"`
}

type Tag struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
