// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToPlan = `-- name: AddTagToPlan :exec

INSERT INTO plan_tags (plan_id, tag_id, assigned_at)
VALUES ($1, $2, $3)
`

type AddTagToPlanParams struct {
	PlanID     int64              `json:"plan_id"`
	TagID      int64              `json:"tag_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

// Plan-Tag association queries
func (q *Queries) AddTagToPlan(ctx context.Context, arg AddTagToPlanParams) error {
	_, err := q.db.Exec(ctx, addTagToPlan, arg.PlanID, arg.TagID, arg.AssignedAt)
	return err
}

const cancelScheduledJob = `-- name: CancelScheduledJob :exec
UPDATE scheduled_jobs
SET cancelled = true
WHERE job_id = $1
`

func (q *Queries) CancelScheduledJob(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelScheduledJob, jobID)
	return err
}

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllConnectorSettings = `-- name: DeleteAllConnectorSettings :exec
DELETE FROM connector_settings WHERE connector_name = $1
`

func (q *Queries) DeleteAllConnectorSettings(ctx context.Context, connectorName string) error {
	_, err := q.db.Exec(ctx, deleteAllConnectorSettings, connectorName)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors WHERE name = $1
`

func (q *Queries) DeleteConnector(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteConnector, name)
	return err
}

const deleteConnectorSetting = `-- name: DeleteConnectorSetting :exec
DELETE FROM connector_settings WHERE connector_name = $1 AND setting_key = $2
`

type DeleteConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

func (q *Queries) DeleteConnectorSetting(ctx context.Context, arg DeleteConnectorSettingParams) error {
	_, err := q.db.Exec(ctx, deleteConnectorSetting, arg.ConnectorName, arg.SettingKey)
	return err
}

const deleteExecutionsByJobID = `-- name: DeleteExecutionsByJobID :exec
DELETE FROM job_executions WHERE job_id = $1
`

func (q *Queries) DeleteExecutionsByJobID(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExecutionsByJobID, jobID)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM background_jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE file_name = $1
`

func (q *Queries) DeletePlan(ctx context.Context, fileName string) error {
	_, err := q.db.Exec(ctx, deletePlan, fileName)
	return err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :exec
DELETE FROM scheduled_jobs WHERE job_id = $1
`

func (q *Queries) DeleteScheduledJob(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduledJob, jobID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE variable_name = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, variableName string) error {
	_, err := q.db.Exec(ctx, deleteSetting, variableName)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const deleteVersionsOlderThan = `-- name: DeleteVersionsOlderThan :exec
DELETE FROM plan_versions
WHERE plan_id = $1 AND version_number <= $2
`

type DeleteVersionsOlderThanParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) DeleteVersionsOlderThan(ctx context.Context, arg DeleteVersionsOlderThanParams) error {
	_, err := q.db.Exec(ctx, deleteVersionsOlderThan, arg.PlanID, arg.VersionNumber)
	return err
}

const disableAllConnectors = `-- name: DisableAllConnectors :exec
UPDATE connectors SET enabled = FALSE, updated_at = NOW()
`

func (q *Queries) DisableAllConnectors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disableAllConnectors)
	return err
}

const getConnectorByName = `-- name: GetConnectorByName :one

SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE name = $1
`

// Connector queries
func (q *Queries) GetConnectorByName(ctx context.Context, name string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByName, name)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorSetting = `-- name: GetConnectorSetting :one

SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = $1 AND setting_key = $2
`

type GetConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

// Connector settings queries
func (q *Queries) GetConnectorSetting(ctx context.Context, arg GetConnectorSettingParams) (ConnectorSetting, error) {
	row := q.db.QueryRow(ctx, getConnectorSetting, arg.ConnectorName, arg.SettingKey)
	var i ConnectorSetting
	err := row.Scan(
		&i.ID,
		&i.ConnectorName,
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
	)
	return i, err
}

const getEnabledConnector = `-- name: GetEnabledConnector :one
SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE enabled = TRUE LIMIT 1
`

func (q *Queries) GetEnabledConnector(ctx context.Context) (Connector, error) {
	row := q.db.QueryRow(ctx, getEnabledConnector)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by FROM job_executions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id pgtype.UUID) (JobExecution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ExecutionNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (BackgroundJob, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.AgentProvider,
		&i.AgentConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) FROM plan_versions WHERE plan_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, planID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumber, planID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getNextExecutionNumber = `-- name: GetNextExecutionNumber :one
SELECT COALESCE(MAX(execution_number), 0) + 1 AS next_number
FROM job_executions
WHERE job_id = $1
`

func (q *Queries) GetNextExecutionNumber(ctx context.Context, jobID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextExecutionNumber, jobID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getPlanByFileName = `-- name: GetPlanByFileName :one
SELECT id, file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE file_name = $1 LIMIT 1
`

func (q *Queries) GetPlanByFileName(ctx context.Context, fileName string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByFileName, fileName)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanTags = `-- name: GetPlanTags :many
SELECT t.id, t.name, t.description, t.color, t.created_at, t.updated_at FROM tags t
JOIN plan_tags pt ON t.id = pt.tag_id
WHERE pt.plan_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetPlanTags(ctx context.Context, planID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getPlanTags, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanVersionByNumber = `-- name: GetPlanVersionByNumber :one
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1 AND version_number = $2
LIMIT 1
`

type GetPlanVersionByNumberParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) GetPlanVersionByNumber(ctx context.Context, arg GetPlanVersionByNumberParams) (PlanVersion, error) {
	row := q.db.QueryRow(ctx, getPlanVersionByNumber, arg.PlanID, arg.VersionNumber)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.VersionNumber,
		&i.FilePath,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanVersionHistory = `-- name: GetPlanVersionHistory :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1
ORDER BY version_number DESC
LIMIT $2 OFFSET $3
`

type GetPlanVersionHistoryParams struct {
	PlanID int64 `json:"plan_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPlanVersionHistory(ctx context.Context, arg GetPlanVersionHistoryParams) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, getPlanVersionHistory, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansWithTag = `-- name: GetPlansWithTag :many
SELECT p.id, p.file_name, p.title, p.created_at, p.modified_at, p.file_size, p.word_count
FROM plans p
JOIN plan_tags pt ON p.id = pt.plan_id
WHERE pt.tag_id = $1
ORDER BY p.modified_at DESC
`

type GetPlansWithTagRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) GetPlansWithTag(ctx context.Context, tagID int64) ([]GetPlansWithTagRow, error) {
	rows, err := q.db.Query(ctx, getPlansWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlansWithTagRow{}
	for rows.Next() {
		var i GetPlansWithTagRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledJobByJobID = `-- name: GetScheduledJobByJobID :one
SELECT id, job_id, scheduled_at, cancelled, created_at FROM scheduled_jobs WHERE job_id = $1 LIMIT 1
`

func (q *Queries) GetScheduledJobByJobID(ctx context.Context, jobID pgtype.UUID) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJobByJobID, jobID)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.Cancelled,
		&i.CreatedAt,
	)
	return i, err
}

const getSettingByName = `-- name: GetSettingByName :one
SELECT variable_name, variable_type, string_value, number_value, boolean_value, datetime_value FROM settings WHERE variable_name = $1 LIMIT 1
`

func (q *Queries) GetSettingByName(ctx context.Context, variableName string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByName, variableName)
	var i Setting
	err := row.Scan(
		&i.VariableName,
		&i.VariableType,
		&i.StringValue,
		&i.NumberValue,
		&i.BooleanValue,
		&i.DatetimeValue,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE name = $1 LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVersionCount = `-- name: GetVersionCount :one
SELECT COUNT(*) FROM plan_versions WHERE plan_id = $1
`

func (q *Queries) GetVersionCount(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getVersionCount, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertExecution = `-- name: InsertExecution :one

INSERT INTO job_executions (id, job_id, execution_number, status, triggered_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by
`

type InsertExecutionParams struct {
	ID              pgtype.UUID `json:"id"`
	JobID           pgtype.UUID `json:"job_id"`
	ExecutionNumber int64       `json:"execution_number"`
	Status          string      `json:"status"`
	TriggeredBy     string      `json:"triggered_by"`
}

// Job Executions
func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) (JobExecution, error) {
	row := q.db.QueryRow(ctx, insertExecution,
		arg.ID,
		arg.JobID,
		arg.ExecutionNumber,
		arg.Status,
		arg.TriggeredBy,
	)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ExecutionNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one

INSERT INTO background_jobs (id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at
`

type InsertJobParams struct {
	ID            pgtype.UUID      `json:"id"`
	PlanID        int64            `json:"plan_id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	AgentProvider string           `json:"agent_provider"`
	AgentConfig   string           `json:"agent_config"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// Background Jobs
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (BackgroundJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.PlanID,
		arg.Name,
		arg.Description,
		arg.AgentProvider,
		arg.AgentConfig,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BackgroundJob
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Description,
		&i.AgentProvider,
		&i.AgentConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO plans (file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPlanParams struct {
	FileName   string             `json:"file_name"`
	FilePath   string             `json:"file_path"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.Exec(ctx, insertPlan,
		arg.FileName,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
	)
	return err
}

const insertPlanVersion = `-- name: InsertPlanVersion :exec
INSERT INTO plan_versions (plan_id, version_number, file_path, content, word_count, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPlanVersionParams struct {
	PlanID        int64              `json:"plan_id"`
	VersionNumber int64              `json:"version_number"`
	FilePath      string             `json:"file_path"`
	Content       string             `json:"content"`
	WordCount     int64              `json:"word_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlanVersion(ctx context.Context, arg InsertPlanVersionParams) error {
	_, err := q.db.Exec(ctx, insertPlanVersion,
		arg.PlanID,
		arg.VersionNumber,
		arg.FilePath,
		arg.Content,
		arg.WordCount,
		arg.CreatedAt,
	)
	return err
}

const insertScheduledJob = `-- name: InsertScheduledJob :one

INSERT INTO scheduled_jobs (id, job_id, scheduled_at, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, scheduled_at, cancelled, created_at
`

type InsertScheduledJobParams struct {
	ID          pgtype.UUID      `json:"id"`
	JobID       pgtype.UUID      `json:"job_id"`
	ScheduledAt pgtype.Timestamp `json:"scheduled_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// Scheduled Jobs
func (q *Queries) InsertScheduledJob(ctx context.Context, arg InsertScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, insertScheduledJob,
		arg.ID,
		arg.JobID,
		arg.ScheduledAt,
		arg.CreatedAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.Cancelled,
		&i.CreatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO tags (name, description, color, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, color, created_at, updated_at
`

type InsertTagParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Tag queries
func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
`

type ListAllPlansRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansRow{}
	for rows.Next() {
		var i ListAllPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithPagination = `-- name: ListAllPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPlansWithPaginationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllPlansWithPaginationRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) ListAllPlansWithPagination(ctx context.Context, arg ListAllPlansWithPaginationParams) ([]ListAllPlansWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, listAllPlansWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithPaginationRow{}
	for rows.Next() {
		var i ListAllPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithTags = `-- name: ListAllPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    t.tag_ids,
    t.tag_names
FROM plans p
         LEFT JOIN (
    SELECT
        pt.plan_id,
        array_agg(DISTINCT t.id ORDER BY t.id)::int4[] AS tag_ids,
        array_agg(DISTINCT t.name ORDER BY t.name)::text[] AS tag_names

    FROM plan_tags pt
             JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
ORDER BY p.id
`

type ListAllPlansWithTagsRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	TagIds     []int32            `json:"tag_ids"`
	TagNames   []string           `json:"tag_names"`
}

func (q *Queries) ListAllPlansWithTags(ctx context.Context) ([]ListAllPlansWithTagsRow, error) {
	rows, err := q.db.Query(ctx, listAllPlansWithTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithTagsRow{}
	for rows.Next() {
		var i ListAllPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, description, color, created_at, updated_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorSettings = `-- name: ListConnectorSettings :many
SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = $1
`

func (q *Queries) ListConnectorSettings(ctx context.Context, connectorName string) ([]ConnectorSetting, error) {
	rows, err := q.db.Query(ctx, listConnectorSettings, connectorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorSetting{}
	for rows.Next() {
		var i ConnectorSetting
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorName,
			&i.SettingKey,
			&i.SettingValue,
			&i.IsSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT name, display_name, enabled, created_at, updated_at FROM connectors ORDER BY name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueScheduledJobs = `-- name: ListDueScheduledJobs :many
SELECT id, job_id, scheduled_at, cancelled, created_at FROM scheduled_jobs
WHERE scheduled_at <= $1 AND cancelled = false
`

func (q *Queries) ListDueScheduledJobs(ctx context.Context, scheduledAt pgtype.Timestamp) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, listDueScheduledJobs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ScheduledAt,
			&i.Cancelled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByJobID = `-- name: ListExecutionsByJobID :many
SELECT id, job_id, execution_number, status, started_at, completed_at, exit_code, output_log, error_message, triggered_by FROM job_executions
WHERE job_id = $1
ORDER BY execution_number DESC
LIMIT $2 OFFSET $3
`

type ListExecutionsByJobIDParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListExecutionsByJobID(ctx context.Context, arg ListExecutionsByJobIDParams) ([]JobExecution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByJobID, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobExecution{}
	for rows.Next() {
		var i JobExecution
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ExecutionNumber,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.OutputLog,
			&i.ErrorMessage,
			&i.TriggeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsWithJobs = `-- name: ListExecutionsWithJobs :many
SELECT
    e.id AS execution_id,
    e.job_id,
    e.execution_number,
    e.status AS execution_status,
    e.started_at,
    e.completed_at,
    e.exit_code,
    e.output_log,
    e.error_message,
    e.triggered_by,
    j.name AS job_name,
    p.file_name AS plan_file_name
FROM job_executions e
JOIN background_jobs j ON e.job_id = j.id
JOIN plans p ON j.plan_id = p.id
ORDER BY e.started_at DESC
LIMIT $1 OFFSET $2
`

type ListExecutionsWithJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListExecutionsWithJobsRow struct {
	ExecutionID     pgtype.UUID      `json:"execution_id"`
	JobID           pgtype.UUID      `json:"job_id"`
	ExecutionNumber int64            `json:"execution_number"`
	ExecutionStatus string           `json:"execution_status"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	CompletedAt     pgtype.Timestamp `json:"completed_at"`
	ExitCode        pgtype.Int4      `json:"exit_code"`
	OutputLog       pgtype.Text      `json:"output_log"`
	ErrorMessage    pgtype.Text      `json:"error_message"`
	TriggeredBy     string           `json:"triggered_by"`
	JobName         string           `json:"job_name"`
	PlanFileName    string           `json:"plan_file_name"`
}

func (q *Queries) ListExecutionsWithJobs(ctx context.Context, arg ListExecutionsWithJobsParams) ([]ListExecutionsWithJobsRow, error) {
	rows, err := q.db.Query(ctx, listExecutionsWithJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsWithJobsRow{}
	for rows.Next() {
		var i ListExecutionsWithJobsRow
		if err := rows.Scan(
			&i.ExecutionID,
			&i.JobID,
			&i.ExecutionNumber,
			&i.ExecutionStatus,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExitCode,
			&i.OutputLog,
			&i.ErrorMessage,
			&i.TriggeredBy,
			&i.JobName,
			&i.PlanFileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]BackgroundJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByPlanID = `-- name: ListJobsByPlanID :many
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs
WHERE plan_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByPlanIDParams struct {
	PlanID int64 `json:"plan_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobsByPlanID(ctx context.Context, arg ListJobsByPlanIDParams) ([]BackgroundJob, error) {
	rows, err := q.db.Query(ctx, listJobsByPlanID, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, plan_id, name, description, agent_provider, agent_config, status, created_at, updated_at, last_run_at FROM background_jobs
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]BackgroundJob, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackgroundJob{}
	for rows.Next() {
		var i BackgroundJob
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Description,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithPlans = `-- name: ListJobsWithPlans :many

SELECT
    j.id AS job_id,
    j.plan_id,
    j.name AS job_name,
    j.description AS job_description,
    j.agent_provider,
    j.agent_config,
    j.status,
    j.created_at AS job_created_at,
    j.updated_at AS job_updated_at,
    j.last_run_at,
    p.file_name AS plan_file_name,
    p.file_path AS plan_file_path,
    p.title AS plan_title
FROM background_jobs j
JOIN plans p ON j.plan_id = p.id
ORDER BY j.created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsWithPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListJobsWithPlansRow struct {
	JobID          pgtype.UUID      `json:"job_id"`
	PlanID         int64            `json:"plan_id"`
	JobName        string           `json:"job_name"`
	JobDescription pgtype.Text      `json:"job_description"`
	AgentProvider  string           `json:"agent_provider"`
	AgentConfig    string           `json:"agent_config"`
	Status         string           `json:"status"`
	JobCreatedAt   pgtype.Timestamp `json:"job_created_at"`
	JobUpdatedAt   pgtype.Timestamp `json:"job_updated_at"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
	PlanFileName   string           `json:"plan_file_name"`
	PlanFilePath   string           `json:"plan_file_path"`
	PlanTitle      string           `json:"plan_title"`
}

// Job queries with joins
func (q *Queries) ListJobsWithPlans(ctx context.Context, arg ListJobsWithPlansParams) ([]ListJobsWithPlansRow, error) {
	rows, err := q.db.Query(ctx, listJobsWithPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsWithPlansRow{}
	for rows.Next() {
		var i ListJobsWithPlansRow
		if err := rows.Scan(
			&i.JobID,
			&i.PlanID,
			&i.JobName,
			&i.JobDescription,
			&i.AgentProvider,
			&i.AgentConfig,
			&i.Status,
			&i.JobCreatedAt,
			&i.JobUpdatedAt,
			&i.LastRunAt,
			&i.PlanFileName,
			&i.PlanFilePath,
			&i.PlanTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPlansFromTag = `-- name: RemoveAllPlansFromTag :exec
DELETE FROM plan_tags WHERE tag_id = $1
`

func (q *Queries) RemoveAllPlansFromTag(ctx context.Context, tagID int64) error {
	_, err := q.db.Exec(ctx, removeAllPlansFromTag, tagID)
	return err
}

const removeAllTagsFromPlan = `-- name: RemoveAllTagsFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = $1
`

func (q *Queries) RemoveAllTagsFromPlan(ctx context.Context, planID int64) error {
	_, err := q.db.Exec(ctx, removeAllTagsFromPlan, planID)
	return err
}

const removeTagFromPlan = `-- name: RemoveTagFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = $1 AND tag_id = $2
`

type RemoveTagFromPlanParams struct {
	PlanID int64 `json:"plan_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPlan(ctx context.Context, arg RemoveTagFromPlanParams) error {
	_, err := q.db.Exec(ctx, removeTagFromPlan, arg.PlanID, arg.TagID)
	return err
}

const searchPlans = `-- name: SearchPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE $1 OR content LIKE $2
ORDER BY modified_at DESC
`

type SearchPlansParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) SearchPlans(ctx context.Context, arg SearchPlansParams) ([]SearchPlansRow, error) {
	rows, err := q.db.Query(ctx, searchPlans, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansRow{}
	for rows.Next() {
		var i SearchPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithPagination = `-- name: SearchPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE $1 OR content LIKE $2
ORDER BY modified_at DESC
LIMIT $3 OFFSET $4
`

type SearchPlansWithPaginationParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchPlansWithPaginationRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) SearchPlansWithPagination(ctx context.Context, arg SearchPlansWithPaginationParams) ([]SearchPlansWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, searchPlansWithPagination,
		arg.Title,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithPaginationRow{}
	for rows.Next() {
		var i SearchPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithTags = `-- name: SearchPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    t.tag_ids,
    t.tag_names
FROM plans p
         LEFT JOIN (
    SELECT
        pt.plan_id,
        array_agg(DISTINCT t.id ORDER BY t.id)::int4[] AS tag_ids,
        array_agg(DISTINCT t.name ORDER BY t.name)::text[] AS tag_names
    FROM plan_tags pt
             JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
WHERE p.title LIKE $1 OR p.content LIKE $2
ORDER BY p.modified_at DESC
`

type SearchPlansWithTagsParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansWithTagsRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	TagIds     []int32            `json:"tag_ids"`
	TagNames   []string           `json:"tag_names"`
}

func (q *Queries) SearchPlansWithTags(ctx context.Context, arg SearchPlansWithTagsParams) ([]SearchPlansWithTagsRow, error) {
	rows, err := q.db.Query(ctx, searchPlansWithTags, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithTagsRow{}
	for rows.Next() {
		var i SearchPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVersionsByContent = `-- name: SearchVersionsByContent :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1 AND content LIKE $2
ORDER BY version_number DESC
`

type SearchVersionsByContentParams struct {
	PlanID  int64  `json:"plan_id"`
	Content string `json:"content"`
}

func (q *Queries) SearchVersionsByContent(ctx context.Context, arg SearchVersionsByContentParams) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, searchVersionsByContent, arg.PlanID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorEnabled = `-- name: SetConnectorEnabled :exec
UPDATE connectors SET enabled = TRUE, updated_at = NOW() WHERE name = $1
`

func (q *Queries) SetConnectorEnabled(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, setConnectorEnabled, name)
	return err
}

const updateExecution = `-- name: UpdateExecution :exec
UPDATE job_executions
SET status = $1,
    started_at = COALESCE($2, started_at),
    completed_at = COALESCE($3, completed_at),
    exit_code = COALESCE($4, exit_code),
    output_log = COALESCE($5, output_log),
    error_message = COALESCE($6, error_message)
WHERE id = $7
`

type UpdateExecutionParams struct {
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	ExitCode     pgtype.Int4      `json:"exit_code"`
	OutputLog    pgtype.Text      `json:"output_log"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	ID           pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) error {
	_, err := q.db.Exec(ctx, updateExecution,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ExitCode,
		arg.OutputLog,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE background_jobs
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    agent_config = COALESCE($3, agent_config),
    updated_at = $4
WHERE id = $5
`

type UpdateJobParams struct {
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	AgentConfig string           `json:"agent_config"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.Exec(ctx, updateJob,
		arg.Name,
		arg.Description,
		arg.AgentConfig,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE background_jobs
SET status = $1,
    last_run_at = $2,
    updated_at = $3
WHERE id = $4
`

type UpdateJobStatusParams struct {
	Status    string           `json:"status"`
	LastRunAt pgtype.Timestamp `json:"last_run_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ID        pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.Status,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET title = $1, content = $2, modified_at = $3, indexed_at = $4, file_size = $5, word_count = $6
WHERE file_name = $7
`

type UpdatePlanParams struct {
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	FileName   string             `json:"file_name"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.Title,
		arg.Content,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
		arg.FileName,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags
SET name = $1, description = $2, color = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateTagParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	return err
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO connectors (name, display_name, enabled)
VALUES ($1, $2, $3)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at = NOW()
`

type UpsertConnectorParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.Exec(ctx, upsertConnector, arg.Name, arg.DisplayName, arg.Enabled)
	return err
}

const upsertConnectorSetting = `-- name: UpsertConnectorSetting :exec
INSERT INTO connector_settings (connector_name, setting_key, setting_value, is_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT(connector_name, setting_key) DO UPDATE SET
    setting_value = excluded.setting_value,
    is_secret = excluded.is_secret
`

type UpsertConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

func (q *Queries) UpsertConnectorSetting(ctx context.Context, arg UpsertConnectorSettingParams) error {
	_, err := q.db.Exec(ctx, upsertConnectorSetting,
		arg.ConnectorName,
		arg.SettingKey,
		arg.SettingValue,
		arg.IsSecret,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (variable_name, variable_type, string_value, number_value, boolean_value, datetime_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(variable_name) DO UPDATE SET
    variable_type = excluded.variable_type,
    string_value = excluded.string_value,
    number_value = excluded.number_value,
    boolean_value = excluded.boolean_value,
    datetime_value = excluded.datetime_value
`

type UpsertSettingParams struct {
	VariableName  string             `json:"variable_name"`
	VariableType  string             `json:"variable_type"`
	StringValue   pgtype.Text        `json:"string_value"`
	NumberValue   pgtype.Float8      `json:"number_value"`
	BooleanValue  pgtype.Bool        `json:"boolean_value"`
	DatetimeValue pgtype.Timestamptz `json:"datetime_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.VariableName,
		arg.VariableType,
		arg.StringValue,
		arg.NumberValue,
		arg.BooleanValue,
		arg.DatetimeValue,
	)
	return err
}
