// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToPlan = `-- name: AddTagToPlan :exec

INSERT INTO plan_tags (plan_id, tag_id, assigned_at)
VALUES ($1, $2, $3)
`

type AddTagToPlanParams struct {
	PlanID     int64              `json:"plan_id"`
	TagID      int64              `json:"tag_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

// Plan-Tag association queries
func (q *Queries) AddTagToPlan(ctx context.Context, arg AddTagToPlanParams) error {
	_, err := q.db.Exec(ctx, addTagToPlan, arg.PlanID, arg.TagID, arg.AssignedAt)
	return err
}

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllConnectorSettings = `-- name: DeleteAllConnectorSettings :exec
DELETE FROM connector_settings WHERE connector_name = $1
`

func (q *Queries) DeleteAllConnectorSettings(ctx context.Context, connectorName string) error {
	_, err := q.db.Exec(ctx, deleteAllConnectorSettings, connectorName)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors WHERE name = $1
`

func (q *Queries) DeleteConnector(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteConnector, name)
	return err
}

const deleteConnectorSetting = `-- name: DeleteConnectorSetting :exec
DELETE FROM connector_settings WHERE connector_name = $1 AND setting_key = $2
`

type DeleteConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

func (q *Queries) DeleteConnectorSetting(ctx context.Context, arg DeleteConnectorSettingParams) error {
	_, err := q.db.Exec(ctx, deleteConnectorSetting, arg.ConnectorName, arg.SettingKey)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE file_name = $1
`

func (q *Queries) DeletePlan(ctx context.Context, fileName string) error {
	_, err := q.db.Exec(ctx, deletePlan, fileName)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionFileChanges = `-- name: DeleteSessionFileChanges :exec
DELETE FROM session_file_changes WHERE session_id = $1
`

func (q *Queries) DeleteSessionFileChanges(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionFileChanges, sessionID)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM session_messages WHERE session_id = $1
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, sessionID)
	return err
}

const deleteSessionTodos = `-- name: DeleteSessionTodos :exec
DELETE FROM session_todos WHERE session_id = $1
`

func (q *Queries) DeleteSessionTodos(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionTodos, sessionID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE variable_name = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, variableName string) error {
	_, err := q.db.Exec(ctx, deleteSetting, variableName)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const deleteVersionsOlderThan = `-- name: DeleteVersionsOlderThan :exec
DELETE FROM plan_versions
WHERE plan_id = $1 AND version_number <= $2
`

type DeleteVersionsOlderThanParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) DeleteVersionsOlderThan(ctx context.Context, arg DeleteVersionsOlderThanParams) error {
	_, err := q.db.Exec(ctx, deleteVersionsOlderThan, arg.PlanID, arg.VersionNumber)
	return err
}

const disableAllConnectors = `-- name: DisableAllConnectors :exec
UPDATE connectors SET enabled = FALSE, updated_at = NOW()
`

func (q *Queries) DisableAllConnectors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disableAllConnectors)
	return err
}

const getConnectorByName = `-- name: GetConnectorByName :one

SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE name = $1
`

// Connector queries
func (q *Queries) GetConnectorByName(ctx context.Context, name string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByName, name)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorSetting = `-- name: GetConnectorSetting :one

SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = $1 AND setting_key = $2
`

type GetConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
}

// Connector settings queries
func (q *Queries) GetConnectorSetting(ctx context.Context, arg GetConnectorSettingParams) (ConnectorSetting, error) {
	row := q.db.QueryRow(ctx, getConnectorSetting, arg.ConnectorName, arg.SettingKey)
	var i ConnectorSetting
	err := row.Scan(
		&i.ID,
		&i.ConnectorName,
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
	)
	return i, err
}

const getEnabledConnector = `-- name: GetEnabledConnector :one
SELECT name, display_name, enabled, created_at, updated_at FROM connectors WHERE enabled = TRUE LIMIT 1
`

func (q *Queries) GetEnabledConnector(ctx context.Context) (Connector, error) {
	row := q.db.QueryRow(ctx, getEnabledConnector)
	var i Connector
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) FROM plan_versions WHERE plan_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, planID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumber, planID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPlanByFileName = `-- name: GetPlanByFileName :one
SELECT id, file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE file_name = $1 LIMIT 1
`

func (q *Queries) GetPlanByFileName(ctx context.Context, fileName string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByFileName, fileName)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count FROM plans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int32) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IndexedAt,
		&i.FileSize,
		&i.WordCount,
	)
	return i, err
}

const getPlanTags = `-- name: GetPlanTags :many
SELECT t.id, t.name, t.description, t.color, t.created_at, t.updated_at FROM tags t
JOIN plan_tags pt ON t.id = pt.tag_id
WHERE pt.plan_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetPlanTags(ctx context.Context, planID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getPlanTags, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanVersionByNumber = `-- name: GetPlanVersionByNumber :one
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1 AND version_number = $2
LIMIT 1
`

type GetPlanVersionByNumberParams struct {
	PlanID        int64 `json:"plan_id"`
	VersionNumber int64 `json:"version_number"`
}

func (q *Queries) GetPlanVersionByNumber(ctx context.Context, arg GetPlanVersionByNumberParams) (PlanVersion, error) {
	row := q.db.QueryRow(ctx, getPlanVersionByNumber, arg.PlanID, arg.VersionNumber)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.VersionNumber,
		&i.FilePath,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanVersionHistory = `-- name: GetPlanVersionHistory :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1
ORDER BY version_number DESC
LIMIT $2 OFFSET $3
`

type GetPlanVersionHistoryParams struct {
	PlanID int64 `json:"plan_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPlanVersionHistory(ctx context.Context, arg GetPlanVersionHistoryParams) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, getPlanVersionHistory, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansWithTag = `-- name: GetPlansWithTag :many
SELECT p.id, p.file_name, p.title, p.created_at, p.modified_at, p.file_size, p.word_count
FROM plans p
JOIN plan_tags pt ON p.id = pt.plan_id
WHERE pt.tag_id = $1
ORDER BY p.modified_at DESC
`

type GetPlansWithTagRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) GetPlansWithTag(ctx context.Context, tagID int64) ([]GetPlansWithTagRow, error) {
	rows, err := q.db.Query(ctx, getPlansWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlansWithTagRow{}
	for rows.Next() {
		var i GetPlansWithTagRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, session_uuid, project_path, project_name, jsonl_file_path, plan_id, status, message_count, first_message_at, last_message_at, created_at, updated_at, cwd, git_branch, slug FROM sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionUuid,
		&i.ProjectPath,
		&i.ProjectName,
		&i.JsonlFilePath,
		&i.PlanID,
		&i.Status,
		&i.MessageCount,
		&i.FirstMessageAt,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cwd,
		&i.GitBranch,
		&i.Slug,
	)
	return i, err
}

const getSessionByUUID = `-- name: GetSessionByUUID :one
SELECT id, session_uuid, project_path, project_name, jsonl_file_path, plan_id, status, message_count, first_message_at, last_message_at, created_at, updated_at, cwd, git_branch, slug FROM sessions WHERE session_uuid = $1 LIMIT 1
`

func (q *Queries) GetSessionByUUID(ctx context.Context, sessionUuid string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByUUID, sessionUuid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionUuid,
		&i.ProjectPath,
		&i.ProjectName,
		&i.JsonlFilePath,
		&i.PlanID,
		&i.Status,
		&i.MessageCount,
		&i.FirstMessageAt,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cwd,
		&i.GitBranch,
		&i.Slug,
	)
	return i, err
}

const getSessionFileChanges = `-- name: GetSessionFileChanges :many
SELECT id, session_id, message_id, file_path, change_type, detected_at FROM session_file_changes
WHERE session_id = $1
ORDER BY detected_at DESC
`

func (q *Queries) GetSessionFileChanges(ctx context.Context, sessionID int64) ([]SessionFileChange, error) {
	rows, err := q.db.Query(ctx, getSessionFileChanges, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionFileChange{}
	for rows.Next() {
		var i SessionFileChange
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.FilePath,
			&i.ChangeType,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionMessageCount = `-- name: GetSessionMessageCount :one
SELECT COUNT(*) FROM session_messages WHERE session_id = $1
`

func (q *Queries) GetSessionMessageCount(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionMessageCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, message_uuid, parent_uuid, message_type, message_subtype, content, role, timestamp, cwd, git_branch, is_meta, is_sidechain, created_at FROM session_messages
WHERE session_id = $1
ORDER BY timestamp ASC
LIMIT $2 OFFSET $3
`

type GetSessionMessagesParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetSessionMessages(ctx context.Context, arg GetSessionMessagesParams) ([]SessionMessage, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageUuid,
			&i.ParentUuid,
			&i.MessageType,
			&i.MessageSubtype,
			&i.Content,
			&i.Role,
			&i.Timestamp,
			&i.Cwd,
			&i.GitBranch,
			&i.IsMeta,
			&i.IsSidechain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionTodos = `-- name: GetSessionTodos :many
SELECT id, session_id, message_id, content, status, active_form, created_at, updated_at FROM session_todos
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSessionTodos(ctx context.Context, sessionID int64) ([]SessionTodo, error) {
	rows, err := q.db.Query(ctx, getSessionTodos, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionTodo{}
	for rows.Next() {
		var i SessionTodo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Content,
			&i.Status,
			&i.ActiveForm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByName = `-- name: GetSettingByName :one
SELECT variable_name, variable_type, string_value, number_value, boolean_value, datetime_value FROM settings WHERE variable_name = $1 LIMIT 1
`

func (q *Queries) GetSettingByName(ctx context.Context, variableName string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByName, variableName)
	var i Setting
	err := row.Scan(
		&i.VariableName,
		&i.VariableType,
		&i.StringValue,
		&i.NumberValue,
		&i.BooleanValue,
		&i.DatetimeValue,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, color, created_at, updated_at FROM tags WHERE name = $1 LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVersionCount = `-- name: GetVersionCount :one
SELECT COUNT(*) FROM plan_versions WHERE plan_id = $1
`

func (q *Queries) GetVersionCount(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getVersionCount, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO plans (file_name, file_path, title, content, created_at, modified_at, indexed_at, file_size, word_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPlanParams struct {
	FileName   string             `json:"file_name"`
	FilePath   string             `json:"file_path"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.Exec(ctx, insertPlan,
		arg.FileName,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
	)
	return err
}

const insertPlanVersion = `-- name: InsertPlanVersion :exec
INSERT INTO plan_versions (plan_id, version_number, file_path, content, word_count, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPlanVersionParams struct {
	PlanID        int64              `json:"plan_id"`
	VersionNumber int64              `json:"version_number"`
	FilePath      string             `json:"file_path"`
	Content       string             `json:"content"`
	WordCount     int64              `json:"word_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlanVersion(ctx context.Context, arg InsertPlanVersionParams) error {
	_, err := q.db.Exec(ctx, insertPlanVersion,
		arg.PlanID,
		arg.VersionNumber,
		arg.FilePath,
		arg.Content,
		arg.WordCount,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO sessions (session_uuid, project_path, project_name, jsonl_file_path, plan_id, status, message_count, first_message_at, last_message_at, created_at, updated_at, cwd, git_branch, slug)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type InsertSessionParams struct {
	SessionUuid    string             `json:"session_uuid"`
	ProjectPath    string             `json:"project_path"`
	ProjectName    string             `json:"project_name"`
	JsonlFilePath  string             `json:"jsonl_file_path"`
	PlanID         pgtype.Int8        `json:"plan_id"`
	Status         string             `json:"status"`
	MessageCount   int64              `json:"message_count"`
	FirstMessageAt pgtype.Timestamptz `json:"first_message_at"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Cwd            pgtype.Text        `json:"cwd"`
	GitBranch      pgtype.Text        `json:"git_branch"`
	Slug           pgtype.Text        `json:"slug"`
}

// Session queries
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.SessionUuid,
		arg.ProjectPath,
		arg.ProjectName,
		arg.JsonlFilePath,
		arg.PlanID,
		arg.Status,
		arg.MessageCount,
		arg.FirstMessageAt,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Cwd,
		arg.GitBranch,
		arg.Slug,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertSessionFileChange = `-- name: InsertSessionFileChange :exec

INSERT INTO session_file_changes (session_id, message_id, file_path, change_type, detected_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSessionFileChangeParams struct {
	SessionID  int64              `json:"session_id"`
	MessageID  pgtype.Int8        `json:"message_id"`
	FilePath   string             `json:"file_path"`
	ChangeType string             `json:"change_type"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

// Session file change queries
func (q *Queries) InsertSessionFileChange(ctx context.Context, arg InsertSessionFileChangeParams) error {
	_, err := q.db.Exec(ctx, insertSessionFileChange,
		arg.SessionID,
		arg.MessageID,
		arg.FilePath,
		arg.ChangeType,
		arg.DetectedAt,
	)
	return err
}

const insertSessionMessage = `-- name: InsertSessionMessage :one

INSERT INTO session_messages (session_id, message_uuid, parent_uuid, message_type, message_subtype, content, role, timestamp, cwd, git_branch, is_meta, is_sidechain, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertSessionMessageParams struct {
	SessionID      int64              `json:"session_id"`
	MessageUuid    string             `json:"message_uuid"`
	ParentUuid     pgtype.Text        `json:"parent_uuid"`
	MessageType    string             `json:"message_type"`
	MessageSubtype pgtype.Text        `json:"message_subtype"`
	Content        pgtype.Text        `json:"content"`
	Role           pgtype.Text        `json:"role"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	Cwd            pgtype.Text        `json:"cwd"`
	GitBranch      pgtype.Text        `json:"git_branch"`
	IsMeta         pgtype.Bool        `json:"is_meta"`
	IsSidechain    pgtype.Bool        `json:"is_sidechain"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Session message queries
func (q *Queries) InsertSessionMessage(ctx context.Context, arg InsertSessionMessageParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSessionMessage,
		arg.SessionID,
		arg.MessageUuid,
		arg.ParentUuid,
		arg.MessageType,
		arg.MessageSubtype,
		arg.Content,
		arg.Role,
		arg.Timestamp,
		arg.Cwd,
		arg.GitBranch,
		arg.IsMeta,
		arg.IsSidechain,
		arg.CreatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertSessionTodo = `-- name: InsertSessionTodo :exec

INSERT INTO session_todos (session_id, message_id, content, status, active_form, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSessionTodoParams struct {
	SessionID  int64              `json:"session_id"`
	MessageID  pgtype.Int8        `json:"message_id"`
	Content    string             `json:"content"`
	Status     string             `json:"status"`
	ActiveForm pgtype.Text        `json:"active_form"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Session todo queries
func (q *Queries) InsertSessionTodo(ctx context.Context, arg InsertSessionTodoParams) error {
	_, err := q.db.Exec(ctx, insertSessionTodo,
		arg.SessionID,
		arg.MessageID,
		arg.Content,
		arg.Status,
		arg.ActiveForm,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO tags (name, description, color, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, color, created_at, updated_at
`

type InsertTagParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Tag queries
func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
`

type ListAllPlansRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansRow{}
	for rows.Next() {
		var i ListAllPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithPagination = `-- name: ListAllPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
ORDER BY modified_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPlansWithPaginationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllPlansWithPaginationRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) ListAllPlansWithPagination(ctx context.Context, arg ListAllPlansWithPaginationParams) ([]ListAllPlansWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, listAllPlansWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithPaginationRow{}
	for rows.Next() {
		var i ListAllPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlansWithTags = `-- name: ListAllPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    t.tag_ids,
    t.tag_names
FROM plans p
         LEFT JOIN (
    SELECT
        pt.plan_id,
        array_agg(DISTINCT t.id ORDER BY t.id)::int4[] AS tag_ids,
        array_agg(DISTINCT t.name ORDER BY t.name)::text[] AS tag_names

    FROM plan_tags pt
             JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
ORDER BY p.id
`

type ListAllPlansWithTagsRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	TagIds     []int32            `json:"tag_ids"`
	TagNames   []string           `json:"tag_names"`
}

func (q *Queries) ListAllPlansWithTags(ctx context.Context) ([]ListAllPlansWithTagsRow, error) {
	rows, err := q.db.Query(ctx, listAllPlansWithTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansWithTagsRow{}
	for rows.Next() {
		var i ListAllPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT
    s.id,
    s.session_uuid,
    s.project_name,
    s.status,
    s.message_count,
    s.last_message_at,
    s.slug,
    p.title AS plan_title
FROM sessions s
LEFT JOIN plans p ON s.plan_id = p.id
ORDER BY s.updated_at DESC
`

type ListAllSessionsRow struct {
	ID            int32              `json:"id"`
	SessionUuid   string             `json:"session_uuid"`
	ProjectName   string             `json:"project_name"`
	Status        string             `json:"status"`
	MessageCount  int64              `json:"message_count"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	Slug          pgtype.Text        `json:"slug"`
	PlanTitle     pgtype.Text        `json:"plan_title"`
}

func (q *Queries) ListAllSessions(ctx context.Context) ([]ListAllSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionsRow{}
	for rows.Next() {
		var i ListAllSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionUuid,
			&i.ProjectName,
			&i.Status,
			&i.MessageCount,
			&i.LastMessageAt,
			&i.Slug,
			&i.PlanTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, description, color, created_at, updated_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorSettings = `-- name: ListConnectorSettings :many
SELECT id, connector_name, setting_key, setting_value, is_secret FROM connector_settings WHERE connector_name = $1
`

func (q *Queries) ListConnectorSettings(ctx context.Context, connectorName string) ([]ConnectorSetting, error) {
	rows, err := q.db.Query(ctx, listConnectorSettings, connectorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorSetting{}
	for rows.Next() {
		var i ConnectorSetting
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorName,
			&i.SettingKey,
			&i.SettingValue,
			&i.IsSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT name, display_name, enabled, created_at, updated_at FROM connectors ORDER BY name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPlanID = `-- name: ListSessionsByPlanID :many
SELECT
    s.id,
    s.session_uuid,
    s.project_name,
    s.status,
    s.message_count,
    s.last_message_at,
    s.slug,
    p.title AS plan_title
FROM sessions s
LEFT JOIN plans p ON s.plan_id = p.id
WHERE s.plan_id = $1
ORDER BY s.updated_at DESC
`

type ListSessionsByPlanIDRow struct {
	ID            int32              `json:"id"`
	SessionUuid   string             `json:"session_uuid"`
	ProjectName   string             `json:"project_name"`
	Status        string             `json:"status"`
	MessageCount  int64              `json:"message_count"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	Slug          pgtype.Text        `json:"slug"`
	PlanTitle     pgtype.Text        `json:"plan_title"`
}

func (q *Queries) ListSessionsByPlanID(ctx context.Context, planID pgtype.Int8) ([]ListSessionsByPlanIDRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByPlanID, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByPlanIDRow{}
	for rows.Next() {
		var i ListSessionsByPlanIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionUuid,
			&i.ProjectName,
			&i.Status,
			&i.MessageCount,
			&i.LastMessageAt,
			&i.Slug,
			&i.PlanTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPlansFromTag = `-- name: RemoveAllPlansFromTag :exec
DELETE FROM plan_tags WHERE tag_id = $1
`

func (q *Queries) RemoveAllPlansFromTag(ctx context.Context, tagID int64) error {
	_, err := q.db.Exec(ctx, removeAllPlansFromTag, tagID)
	return err
}

const removeAllTagsFromPlan = `-- name: RemoveAllTagsFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = $1
`

func (q *Queries) RemoveAllTagsFromPlan(ctx context.Context, planID int64) error {
	_, err := q.db.Exec(ctx, removeAllTagsFromPlan, planID)
	return err
}

const removeTagFromPlan = `-- name: RemoveTagFromPlan :exec
DELETE FROM plan_tags WHERE plan_id = $1 AND tag_id = $2
`

type RemoveTagFromPlanParams struct {
	PlanID int64 `json:"plan_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPlan(ctx context.Context, arg RemoveTagFromPlanParams) error {
	_, err := q.db.Exec(ctx, removeTagFromPlan, arg.PlanID, arg.TagID)
	return err
}

const searchPlans = `-- name: SearchPlans :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE $1 OR content LIKE $2
ORDER BY modified_at DESC
`

type SearchPlansParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) SearchPlans(ctx context.Context, arg SearchPlansParams) ([]SearchPlansRow, error) {
	rows, err := q.db.Query(ctx, searchPlans, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansRow{}
	for rows.Next() {
		var i SearchPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithPagination = `-- name: SearchPlansWithPagination :many
SELECT id, file_name, title, created_at, modified_at, file_size, word_count
FROM plans
WHERE title LIKE $1 OR content LIKE $2
ORDER BY modified_at DESC
LIMIT $3 OFFSET $4
`

type SearchPlansWithPaginationParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchPlansWithPaginationRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
}

func (q *Queries) SearchPlansWithPagination(ctx context.Context, arg SearchPlansWithPaginationParams) ([]SearchPlansWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, searchPlansWithPagination,
		arg.Title,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithPaginationRow{}
	for rows.Next() {
		var i SearchPlansWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansWithTags = `-- name: SearchPlansWithTags :many
SELECT
    p.id,
    p.file_name,
    p.title,
    p.created_at,
    p.modified_at,
    p.file_size,
    p.word_count,
    t.tag_ids,
    t.tag_names
FROM plans p
         LEFT JOIN (
    SELECT
        pt.plan_id,
        array_agg(DISTINCT t.id ORDER BY t.id)::int4[] AS tag_ids,
        array_agg(DISTINCT t.name ORDER BY t.name)::text[] AS tag_names
    FROM plan_tags pt
             JOIN tags t ON pt.tag_id = t.id
    GROUP BY pt.plan_id
) t ON t.plan_id = p.id
WHERE p.title LIKE $1 OR p.content LIKE $2
ORDER BY p.modified_at DESC
`

type SearchPlansWithTagsParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SearchPlansWithTagsRow struct {
	ID         int32              `json:"id"`
	FileName   string             `json:"file_name"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	TagIds     []int32            `json:"tag_ids"`
	TagNames   []string           `json:"tag_names"`
}

func (q *Queries) SearchPlansWithTags(ctx context.Context, arg SearchPlansWithTagsParams) ([]SearchPlansWithTagsRow, error) {
	rows, err := q.db.Query(ctx, searchPlansWithTags, arg.Title, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlansWithTagsRow{}
	for rows.Next() {
		var i SearchPlansWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.FileSize,
			&i.WordCount,
			&i.TagIds,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVersionsByContent = `-- name: SearchVersionsByContent :many
SELECT id, plan_id, version_number, file_path, content, word_count, created_at
FROM plan_versions
WHERE plan_id = $1 AND content LIKE $2
ORDER BY version_number DESC
`

type SearchVersionsByContentParams struct {
	PlanID  int64  `json:"plan_id"`
	Content string `json:"content"`
}

func (q *Queries) SearchVersionsByContent(ctx context.Context, arg SearchVersionsByContentParams) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, searchVersionsByContent, arg.PlanID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.VersionNumber,
			&i.FilePath,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectorEnabled = `-- name: SetConnectorEnabled :exec
UPDATE connectors SET enabled = TRUE, updated_at = NOW() WHERE name = $1
`

func (q *Queries) SetConnectorEnabled(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, setConnectorEnabled, name)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET title = $1, content = $2, modified_at = $3, indexed_at = $4, file_size = $5, word_count = $6
WHERE file_name = $7
`

type UpdatePlanParams struct {
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	IndexedAt  pgtype.Timestamptz `json:"indexed_at"`
	FileSize   int64              `json:"file_size"`
	WordCount  int64              `json:"word_count"`
	FileName   string             `json:"file_name"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.Title,
		arg.Content,
		arg.ModifiedAt,
		arg.IndexedAt,
		arg.FileSize,
		arg.WordCount,
		arg.FileName,
	)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET status = $1, message_count = $2, first_message_at = $3, last_message_at = $4, updated_at = $5, cwd = $6, git_branch = $7
WHERE id = $8
`

type UpdateSessionParams struct {
	Status         string             `json:"status"`
	MessageCount   int64              `json:"message_count"`
	FirstMessageAt pgtype.Timestamptz `json:"first_message_at"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Cwd            pgtype.Text        `json:"cwd"`
	GitBranch      pgtype.Text        `json:"git_branch"`
	ID             int32              `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.Status,
		arg.MessageCount,
		arg.FirstMessageAt,
		arg.LastMessageAt,
		arg.UpdatedAt,
		arg.Cwd,
		arg.GitBranch,
		arg.ID,
	)
	return err
}

const updateSessionTodo = `-- name: UpdateSessionTodo :exec
UPDATE session_todos
SET status = $1, active_form = $2, updated_at = $3
WHERE id = $4
`

type UpdateSessionTodoParams struct {
	Status     string             `json:"status"`
	ActiveForm pgtype.Text        `json:"active_form"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         int32              `json:"id"`
}

func (q *Queries) UpdateSessionTodo(ctx context.Context, arg UpdateSessionTodoParams) error {
	_, err := q.db.Exec(ctx, updateSessionTodo,
		arg.Status,
		arg.ActiveForm,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags
SET name = $1, description = $2, color = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateTagParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	return err
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO connectors (name, display_name, enabled)
VALUES ($1, $2, $3)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at = NOW()
`

type UpsertConnectorParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.Exec(ctx, upsertConnector, arg.Name, arg.DisplayName, arg.Enabled)
	return err
}

const upsertConnectorSetting = `-- name: UpsertConnectorSetting :exec
INSERT INTO connector_settings (connector_name, setting_key, setting_value, is_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT(connector_name, setting_key) DO UPDATE SET
    setting_value = excluded.setting_value,
    is_secret = excluded.is_secret
`

type UpsertConnectorSettingParams struct {
	ConnectorName string `json:"connector_name"`
	SettingKey    string `json:"setting_key"`
	SettingValue  string `json:"setting_value"`
	IsSecret      bool   `json:"is_secret"`
}

func (q *Queries) UpsertConnectorSetting(ctx context.Context, arg UpsertConnectorSettingParams) error {
	_, err := q.db.Exec(ctx, upsertConnectorSetting,
		arg.ConnectorName,
		arg.SettingKey,
		arg.SettingValue,
		arg.IsSecret,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (variable_name, variable_type, string_value, number_value, boolean_value, datetime_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(variable_name) DO UPDATE SET
    variable_type = excluded.variable_type,
    string_value = excluded.string_value,
    number_value = excluded.number_value,
    boolean_value = excluded.boolean_value,
    datetime_value = excluded.datetime_value
`

type UpsertSettingParams struct {
	VariableName  string             `json:"variable_name"`
	VariableType  string             `json:"variable_type"`
	StringValue   pgtype.Text        `json:"string_value"`
	NumberValue   pgtype.Float8      `json:"number_value"`
	BooleanValue  pgtype.Bool        `json:"boolean_value"`
	DatetimeValue pgtype.Timestamptz `json:"datetime_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.VariableName,
		arg.VariableType,
		arg.StringValue,
		arg.NumberValue,
		arg.BooleanValue,
		arg.DatetimeValue,
	)
	return err
}
