// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Javier162380/busquets/internal/connectors (interfaces: Connector)

// Package connectors_test is a generated GoMock package.
package connectors_test

import (
	context "context"
	reflect "reflect"

	connectors "github.com/Javier162380/busquets/internal/connectors"

	gomock "github.com/golang/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// DisplayName mocks base method.
func (m *MockConnector) DisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DisplayName indicates an expected call of DisplayName.
func (mr *MockConnectorMockRecorder) DisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayName", reflect.TypeOf((*MockConnector)(nil).DisplayName))
}

// Name mocks base method.
func (m *MockConnector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockConnectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockConnector)(nil).Name))
}

// RequiredSettings mocks base method.
func (m *MockConnector) RequiredSettings() []connectors.SettingDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiredSettings")
	ret0, _ := ret[0].([]connectors.SettingDefinition)
	return ret0
}

// RequiredSettings indicates an expected call of RequiredSettings.
func (mr *MockConnectorMockRecorder) RequiredSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredSettings", reflect.TypeOf((*MockConnector)(nil).RequiredSettings))
}

// Send mocks base method.
func (m *MockConnector) Send(arg0 context.Context, arg1, arg2 string) (*connectors.SendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connectors.SendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockConnectorMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockConnector)(nil).Send), arg0, arg1, arg2)
}

// Validate mocks base method.
func (m *MockConnector) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConnectorMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConnector)(nil).Validate))
}
