// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Javier162380/busquets/internal/connectors (interfaces: GenerativeConnector)

// Package connectors_test is a generated GoMock package.
package connectors_test

import (
	context "context"
	reflect "reflect"

	connectors "github.com/Javier162380/busquets/internal/connectors"
	gomock "github.com/golang/mock/gomock"
)

// MockGenerativeConnector is a mock of GenerativeConnector interface.
type MockGenerativeConnector struct {
	ctrl     *gomock.Controller
	recorder *MockGenerativeConnectorMockRecorder
}

// MockGenerativeConnectorMockRecorder is the mock recorder for MockGenerativeConnector.
type MockGenerativeConnectorMockRecorder struct {
	mock *MockGenerativeConnector
}

// NewMockGenerativeConnector creates a new mock instance.
func NewMockGenerativeConnector(ctrl *gomock.Controller) *MockGenerativeConnector {
	mock := &MockGenerativeConnector{ctrl: ctrl}
	mock.recorder = &MockGenerativeConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerativeConnector) EXPECT() *MockGenerativeConnectorMockRecorder {
	return m.recorder
}

// DisplayName mocks base method.
func (m *MockGenerativeConnector) DisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DisplayName indicates an expected call of DisplayName.
func (mr *MockGenerativeConnectorMockRecorder) DisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayName", reflect.TypeOf((*MockGenerativeConnector)(nil).DisplayName))
}

// Generate mocks base method.
func (m *MockGenerativeConnector) Generate(arg0 context.Context, arg1 connectors.GeneratorOpts) (*connectors.SendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1)
	ret0, _ := ret[0].(*connectors.SendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGenerativeConnectorMockRecorder) Generate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGenerativeConnector)(nil).Generate), arg0, arg1)
}

// Name mocks base method.
func (m *MockGenerativeConnector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockGenerativeConnectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockGenerativeConnector)(nil).Name))
}

// RequiredSettings mocks base method.
func (m *MockGenerativeConnector) RequiredSettings() []connectors.SettingDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiredSettings")
	ret0, _ := ret[0].([]connectors.SettingDefinition)
	return ret0
}

// RequiredSettings indicates an expected call of RequiredSettings.
func (mr *MockGenerativeConnectorMockRecorder) RequiredSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredSettings", reflect.TypeOf((*MockGenerativeConnector)(nil).RequiredSettings))
}

// Send mocks base method.
func (m *MockGenerativeConnector) Send(arg0 context.Context, arg1, arg2 string) (*connectors.SendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connectors.SendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockGenerativeConnectorMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGenerativeConnector)(nil).Send), arg0, arg1, arg2)
}

// Validate mocks base method.
func (m *MockGenerativeConnector) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockGenerativeConnectorMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGenerativeConnector)(nil).Validate))
}
