// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Javier162380/claude-plan-viewer/cmd/tui/content (interfaces: Displayable)

// Package content_test is a generated GoMock package.
package content_test

import (
	reflect "reflect"

	content "github.com/Javier162380/claude-plan-viewer/cmd/tui/content"
	gomock "github.com/golang/mock/gomock"
)

// MockDisplayable is a mock of Displayable interface.
type MockDisplayable struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayableMockRecorder
}

// MockDisplayableMockRecorder is the mock recorder for MockDisplayable.
type MockDisplayableMockRecorder struct {
	mock *MockDisplayable
}

// NewMockDisplayable creates a new mock instance.
func NewMockDisplayable(ctrl *gomock.Controller) *MockDisplayable {
	mock := &MockDisplayable{ctrl: ctrl}
	mock.recorder = &MockDisplayableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplayable) EXPECT() *MockDisplayableMockRecorder {
	return m.recorder
}

// GetContent mocks base method.
func (m *MockDisplayable) GetContent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContent indicates an expected call of GetContent.
func (mr *MockDisplayableMockRecorder) GetContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockDisplayable)(nil).GetContent))
}

// GetIdentifier mocks base method.
func (m *MockDisplayable) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockDisplayableMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockDisplayable)(nil).GetIdentifier))
}

// GetMetadata mocks base method.
func (m *MockDisplayable) GetMetadata() content.Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(content.Metadata)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockDisplayableMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockDisplayable)(nil).GetMetadata))
}

// GetReadingTime mocks base method.
func (m *MockDisplayable) GetReadingTime() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReadingTime")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetReadingTime indicates an expected call of GetReadingTime.
func (mr *MockDisplayableMockRecorder) GetReadingTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReadingTime", reflect.TypeOf((*MockDisplayable)(nil).GetReadingTime))
}

// GetRenderedHTML mocks base method.
func (m *MockDisplayable) GetRenderedHTML(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRenderedHTML", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRenderedHTML indicates an expected call of GetRenderedHTML.
func (mr *MockDisplayableMockRecorder) GetRenderedHTML(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRenderedHTML", reflect.TypeOf((*MockDisplayable)(nil).GetRenderedHTML), arg0)
}

// GetTitle mocks base method.
func (m *MockDisplayable) GetTitle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTitle")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTitle indicates an expected call of GetTitle.
func (mr *MockDisplayableMockRecorder) GetTitle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTitle", reflect.TypeOf((*MockDisplayable)(nil).GetTitle))
}
